### ISSUE TITLE
Delete leads to whole word being displayed

### ISSUE THREAD

**Issue by oberling** [nanu-c/axolotl#100]
### Description

When deleting a text part in the input field sometimes the whole word gets displayed again and must be deleted again.

### Steps to Reproduce

1. type a sentence of at least 4 words
2. delete two words from the end
3. when trying to delete more the second last word reappears several times while further deleting. It even replaces whole words

**Expected behavior:** I would just want to delete the actual character my cursor is put after

**Actual behavior:** see description

#### Versions

Axolotl Beta 0.7.2.1

#### Device

Nexus 4

**Comment by fabrei** [comment]
Thanks for opening this issue. I already did a [comment for this behaviour](https://github.com/nanu-c/axolotl/issues/73#issuecomment-542419444). It works for me if I turn off spell checking and word suggestion. But it is only a workaround.

**Comment by Blackoverflow** [comment]
My workaround is to select the wrong word and delete that selection.

**Comment by Flaburgan** [comment]
Text suggestion is currently broken in all web app and Morph browser under Ubuntu Touch with the upgrade of QtWebEngine. Hopefully it will be fixed in OTA-14, then we'll see if this issue is still there.

**Comment by nanu-c** [comment]
I close this, because it's a ubuntu touch problem.
