### ISSUE TITLE
Copy Paste not working

### ISSUE THREAD

**Issue by oberling** [nanu-c/axolotl#101]
### Description

Neither copy from nor paste in the input field works

### Steps to Reproduce

1. write some words into the input field 
2. mark them
3. try to copy them
4. try to paste text from somewhere else

**Expected behavior:** context dialog should appear to copy or paste text

**Actual behavior:** nothing appears and copy and paste doesn't work

#### Versions

Axolotl Beta 0.7.2.1

#### Device
Nexus 4

**Comment by fabrei** [comment]
Pasting into the input field of a chat does work with v0.7.4. But sometimes I tried to go to another position of the text by clicking with a finger and I copied my clipboard into it and the whole text vanished. Only because I clicked a millisecond to long. I would expect a little window which is asking: "Paste, Copy, Select,...".

**Comment by nanu-c** [comment]
> Pasting into the input field of a chat does work with v0.7.4. But sometimes I tried to go to another position of the text by clicking with a finger and I copied my clipboard into it and the whole text vanished. Only because I clicked a millisecond to long. I would expect a little window which is asking: "Paste, Copy, Select,...".

Really good idea, i can add that easily

**Comment by vasyugan** [comment]
There is no known workaround to get the text of a received message into the clipboard, is there? In Teleports, you can swipe to the left which brings a copy icon up. Not so in axolotl.

**Comment by Flaburgan** [comment]
With the upgrade of QtWebEngine to 5.14, we now have the cut / copy tooltip freely :)

![screenshot20200926_233315083](https://user-images.githubusercontent.com/930064/94350711-2cdd8c80-0051-11eb-8abc-6c7db0183b5f.png)
