### ISSUE TITLE
Received media cannot be opened/exported but only shown in chat

### ISSUE THREAD

**Issue by oberling** [nanu-c/axolotl#102]
### Description

Received Pictures/Videos and stuff cannot be opened in their appropriate applications

### Steps to Reproduce

1. let someone send you a picture/video
2. try to click/tap on it to get a full screen view or to save it somewhere

**Expected behavior:** a dialog appears to choose to save or open the picture/video

**Actual behavior:** nothing - I still have to look at the tiny picture in the chat window and try to catch every detail

#### Versions

Axolotl Beta 0.7.2.1

#### Device

Nexus 4

**Comment by nanu-c** [comment]
Solved in 0.8.4
