### ISSUE TITLE
URLs not clickable

### ISSUE THREAD

**Issue by oberling** [nanu-c/axolotl#103]
### Description

I cannot open received URLs 

### Steps to Reproduce

1. let someone send you a URL
2. try to open it

**Expected behavior:** the URL should be detected, highlighted and when clicked opened in a Browser

**Actual behavior:** nothing happens and I have to switch back and forth between Axolotl and a Browser to manually type in the whole URL

#### Versions

Axolotl Beta 0.7.2.1

#### Device

Nexus 4

**Comment by nanu-c** [comment]
solved in 0.7.3
