### ISSUE TITLE
Can't add signal desktop

### ISSUE THREAD

**Issue by tux4us** [nanu-c/axolotl#104]
### Description

Scan QR-Code with tagger and past the recieved code in axolotl failed. There is no reaction in axolotl.

### Steps to Reproduce

1. Scan QR-Code with tagger from signal-desktop and copy the recieved code like `tsdevice:/?uuid=X..........`
2. Open axolotl, go to settings and LinkedDevices and "+"
3. Paste the code and tip "Add"

Expected behavior: Add SignalDesktop to Axolotl

Actual behavior: nothing happens

#### Versions

Beta 0.7.2.1

#### Device

Xperia X (5121)

**Comment by nanu-c** [comment]
Actually on my side it works, can you send me some logs?
