### ISSUE TITLE
Groups show wrong members

### ISSUE THREAD

**Issue by Blackoverflow** [nanu-c/axolotl#105]
### Description

The members of groups, listed below the group name, are sometimes from the wrong group (the group opened before).

### Steps to Reproduce

1. Enter a group in axolotl
2. Enter another group

**Expected behavior:**
The members of the second group are listed below the group name.

**Actual behavior:**
The members of the first group are listed.

#### Versions
Axolotl Beta 0.7.4

#### Device
Oneplus One

**Comment by nanu-c** [comment]
solved ib v 0.8.0
