### ISSUE TITLE
[BUG] Cannot pass hCaptcha (presage)

### ISSUE THREAD

**Issue by TriVoxel** [nanu-c/axolotl#1050]
### Description

After attempting to register as phone, I successfully complete the hCaptcha. The "open signal" prompt appears, but clicking it does nothing.

#### Versions

Latest CI clickable build of presage as of writing this.

#### Device

Google Pixel 3a

Ubuntu Touch (focal on dev update channel)

#### Link to Debug Log
Please provide a link to debug from ~/.cache/upstart/application-click-textsecure.nanuc_textsecure*.log
Be careful it contains sensible data

Apparently this folder doesn't exist...?

**Comment by TriVoxel** [comment]
Even when I create upstart folder, no log generated, no log in LogViewer... BTW, am on an LTE nerwork while doing this. Sorry, that's all I got.

**Comment by jonnius** [comment]
On focal, the logs end up in the systemd journal. So command would be `journalctl --user -u lomiri-app-launch--application-click--textsecure.nanuc_textsecure_2.0.0--` or `clickable log` from the repo.

**Comment by jonnius** [comment]
I tried looking into this issue. First thing I found is that what does not seem to be working is some interceptor ([here](https://github.com/nanu-c/axolotl/blob/main/guis/qml/ut/MainUt.qml#L40)) which checks for whether the url is `https://signalcaptchas.org/registration/generate.html`, but what we get is `https://signalcaptchas.org/registration/generate` (without `.html`).

Changing that line results in `[Axolotl Web View] [JS] run interceptor` being printed, but nothing more happens. Apparently calling the interceptor ([here](https://github.com/nanu-c/axolotl/blob/main/guis/qml/ut/MainUt.qml#L71)) simply doesn't work.

**Comment by Haidafraid** [comment]
Ha! I am happy that this issue is already filed. Yes. Same problem here. on a VollaX23 under focal (currently Version 120 RC)

**Comment by jonnius** [comment]
With the latest changes, again I get one step further and I do receive a PIN via SMS. After sending it, I just get an endless spinner. Here are the logs: https://pastebin.com/51Q69trA

**Comment by TriVoxel** [comment]
> With the latest changes, again I get one step further and I do receive a PIN via SMS. After sending it, I just get an endless spinner. There is no error in [the logs](https://pastebin.com/51Q69trA).

Same here. Getting closer, though! Love to see it!

**Comment by mmmilo-tech** [comment]
Hi everyone, I have the same problem on a ubuntu-touch and when I check for libraries I get this :
phablet@ubi$ : ldd ./axolotl
	libtls-padding.so => /usr/lib/arm-linux-gnueabihf/libtls-padding.so (0xb6ecc000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6ea8000)
	libzkgroup_linux_armv7.so => not found
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6dbc000)
	/lib/ld-linux-armhf.so.3 (0xb6ef2000)

Although the supposedly missing lib is in the  lib/arm-linux-gnueabihf/ directory, but not in the lib directories of the device.
Any ideas?

**Comment by jonnius** [comment]
Apps on UT are started with `LD_LIBRARY_PATH` pointing to that directory, so that the app can make use of them. If you started `ldd` with that env var set, it would find them, too.

**Comment by jonnius** [comment]
There is a WIP change (#1085) that somewhat fixes registration. You can get a click from Github Actions or build it yourself with Clickable.

**Comment by moonleay** [comment]
Is there an update on this?
I just installed Ubunbu Touch and I have the same issue.
Additionally the WIP fix, which is metioned here, is not available for download anymore. Is there another link to download the said fix?

**Comment by jonnius** [comment]
We should merge the registration fix. I juts cleaned up the Pull Request. Meanwhile, there are [artefacts](https://github.com/nanu-c/axolotl/actions/runs/6288602167) again.

**Comment by moonleay** [comment]
tysm!
It worked!

**Comment by jonnius** [comment]
This bug is now fixed on the `axolotl_presage` branch.

**Comment by ateliernz** [comment]
What does that mean?

I just installed it on FP4 and i get still stuck on the screen after success with hCaptcha. The button Open Signal does nothing.

**Comment by nanu-c** [comment]
closed with https://github.com/nanu-c/axolotl/releases/tag/v2.0.1
