### ISSUE TITLE
[BUG] Send an attachment does not work

### ISSUE THREAD

**Issue by fabrei** [nanu-c/axolotl#106]
### Description

After the update to v0.7.4, it is not possible to send any attachment to a contact. The app does not crash, but a second window is opened and shows some file manager windows. A screenshot and logfile is attached to this issue. When I close this second window I can still use signal. 

### Steps to Reproduce

1. Open a contact.
2. Press the "+"-button below to send an attachment.
3. A second window shows some file managers.

**Expected behavior:** After pressing the "+"-button, I expect to choose which type of file I will send.

**Actual behavior:** A second window shows some file managers.

#### Versions

v0.7.4

#### Device
Oneplus One Bacon 
UT 16.04 OTA 11

#### Link to Debug Log
[application-click-textsecure.nanuc_textsecure_0.7.4.log](https://github.com/nanu-c/axolotl/files/3991826/application-click-textsecure.nanuc_textsecure_0.7.4.log)

![screenshot20191221_220530404](https://user-images.githubusercontent.com/39765984/71313994-5376f300-2441-11ea-8c23-760d00690c93.png)

**Comment by nanu-c** [comment]
That's my favorite bug, it feels so 90's and it's solved now. Thanks for reporting
