### ISSUE TITLE
Recording Audio Messages

### ISSUE THREAD

**Issue by AA303** [nanu-c/axolotl#108]
There is a button to add audio messages, but when you click on it an incomplete dialogue pop-up comes up. Would it be possible to make it work as expected?
Ubutu Touch on Nexus 5

**Comment by nanu-c** [comment]
For that I have to add c++ code and cmake because there is no pure qml audiorecorder

**Comment by flaun** [comment]
In thr pastor it was possible to send audio messages recorded by the recorder app and send those files via the video button. This doesn't work anymore.
Do you know why? Is it possible to fix at least this easy workaround?

Thanks a lot for your great work!:)

**Comment by nanu-c** [comment]
> In the past it was possible to send audio messages recorded by the recorder app and send those files via the video button. This doesn't work anymore. Do you know why? The other person gets an unknown file. Is it possible to fix at least this easy workaround?
> 
> Thanks a lot for your great work!:)

That I can fix, will be in the next version

**Comment by flaun** [comment]
> > In the past it was possible to send audio messages recorded by the recorder app and send those files via the video button. This doesn't work anymore. Do you know why? The other person gets an unknown file. Is it possible to fix at least this easy workaround?
> > Thanks a lot for your great work!:)
> 
> That I can fix, will be in the next version

This would be awesome:)

**Comment by nanu-c** [comment]
It's done :)

**Comment by AA303** [comment]
Hello @nanu-c 
I have downloaded the update. It does send the file, but on the other end if comes as binary files, that you are unable to play.

![signal-2020-04-09-224632](https://user-images.githubusercontent.com/60611539/78943680-3cbde000-7ab4-11ea-9375-b8dd70a47446.jpeg)

Could you keep this issue as open please?

**Comment by flaun** [comment]
something going on here?
would it be possible to reactivate some code of the past. it worked in a previous version
(unfortunatel I'm not into coding, sorry for this naive question:))

**Comment by Flaburgan** [comment]
I am not aware of anyone working on that feature right now. The coming features (at least the ones I plan to work on) should be status sent / received on outgoing messages, emoji reactions and reply to messages. That should already take some time, so please be patient.

**Comment by nanu-c** [comment]
It's not possible to access the microphone from ubuntu touch webview. Until that isn't fixed it cannot work. The rest is implemented

**Comment by Flaburgan** [comment]
Actually it's implemented but not merged right? We should merge it to avoid conflicts with your patches if we refactor stuff in the future. Unfortunately with a `if` to not show the icon when on UT.

**Comment by nanu-c** [comment]
With the last version and Ubuntu Touch OTA-21 this is now possible. So i am happily going to close this issue.
