### ISSUE TITLE
[BUG] The password page is broken

### ISSUE THREAD

**Issue by Flaburgan** [nanu-c/axolotl#115]
Axolotl 0.7.8.0-pre

![screenshot20200410_231115581](https://user-images.githubusercontent.com/930064/79023809-7f99b980-7b81-11ea-9d3d-727629b01f41.png)

**Comment by nanu-c** [comment]
solved in https://github.com/nanu-c/axolotl/commit/f9e29f1f7442998a934692fecfb62a667ec69e67
