### ISSUE TITLE
[BUG] Makefile:222: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by josch** [nanu-c/axolotl#1160]
When trying to run `make dependencies-deb-arm64` one currently gets:

    Makefile:222: *** missing separator.  Stop.

The issue seems that some lines are indented by two spaces instead of a tab. The issue seems to have been introduced in a6905c176acd6b334e55f6a91e96db414912834e

**Comment by nanu-c** [comment]
i solved it here -> https://github.com/nanu-c/axolotl/commit/69bf5864364e1ba9d158d493bc5c7864b78fe3a9
