### ISSUE TITLE
New Aolotl beta not installable on Ubuntu Touch

### ISSUE THREAD

**Issue by Stevie00911** [nanu-c/axolotl#1220]
### Description

The new Aolotl beta is not installable on Ubuntu Touch.

### Steps to Reproduce

1. Open new Aolotl beta
2. A screen opens to register as a secondary device, see attached screen.
3. A screen opens with a QR code to scan with the primal device, see attached screen.

**Expected behavior:** A nomal registration as a primal device.

**Actual behavior:**  An unpossible registration as a secondary device.
It is not possible to scan a shown QR-code with the same device.

#### Versions
Ubuntu Touch Dev version 680

#### Device
Vollaphone 22

#### Link to Debug Log
![20240403 Vollaphone 22 Axolotl 1](https://github.com/nanu-c/axolotl/assets/45417818/0be9526b-3bec-482b-abd6-b8b98526a802)
![20240403 Vollaphone 22 Axolotl 2](https://github.com/nanu-c/axolotl/assets/45417818/3160df01-b26f-4a7a-8aa1-d0d1eab9a991)

**Comment by nanu-c** [comment]
The screen says, scan this code with your primary device. The primary device is currently signal on android/waydroid or on ios. So this is intended to not work.

**Comment by Stevie00911** [comment]
Hi Aron,
thank you for your info.
But when will there be a functional version for Ubuntu Touch?
I still have a clickable beta installation with the name "Axolotl2", but this version works not correct.
Greetings, Stefan

**Comment by nanu-c** [comment]
The recommended setup is now to 
* install waydroid, then install signal in waydroid from the website https://signal.org/android/apk/
* Register with Signal on waydroid
* start axolotl
* make a screenshot and send it via telegram to a different device
* scan the qr code on a different device with signal in waydroid.
