### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by abkro** [nanu-c/axolotl#126]
### Description

With update to version 0.8.1 sent and received messages are no longer displayed in different colors. They are now both green.

### Steps to Reproduce

1. Enter a chat and read

**Expected behavior:**
Sent and received messages are displayed in different colors so they are easily distinguishable.

#### Versions

0.8.2

#### Device
Nexus 5

**Comment by Flaburgan** [comment]
Indeed, I reproduce that issue. I will fix it.

**Comment by Flaburgan** [comment]
This is now fixed and will be included in the next release. Thank you @abkro for reporting that bug and sorry for the regression.
