### ISSUE TITLE
[BUG] Axolotl closes after a while of running

### ISSUE THREAD

**Issue by fabrei** [nanu-c/axolotl#128]
### Description

Axolotl closes after some hours of being open. It is random how long the app is running if it closes itself. Today I opened the app in the morning and did nothing with the app. I did not receive any message neither I wrote a message. But it also occurs if I interact with it. I put the debug log of today at the end of the issue, maybe it helps.

### Steps to Reproduce

1. Open axolotl.
2. Do nothing or write messages or receive messages.
3. Wait for a couple of hours.
4. The app closes without any reason.

**Expected behavior:** [What you expect to happen]
It keeps running, until I manually close the app.

**Actual behavior:** [What actually happens]
The app closes itself after a while.

#### Versions

0.8.1

#### Device
Oneplus One bacon

#### Link to Debug Log

[application-click-textsecure.nanuc_textsecure_0.8.1.log](https://github.com/nanu-c/axolotl/files/4496783/application-click-textsecure.nanuc_textsecure_0.8.1.log)

**Comment by thilovv** [comment]
I can confirm this issue - OnePlus 3t
I missed some messages...

**Comment by K14D** [comment]
Same here with bq Aquaris E4.5

**Comment by fabrei** [comment]
seems to be fixed for me by latest update to v0.8.2

**Comment by K14D** [comment]
No crashes since update to v.0.8.2 here too.

**Comment by nanu-c** [comment]
Yeai
