### ISSUE TITLE
Add an indicator to know when a picture is uploaded and sent

### ISSUE THREAD

**Issue by flaun** [nanu-c/axolotl#137]
## New description

There is no way for an Axolotl user to know when the upload of the picture sent actually finished, so the user can switch off internet too quick and then the other user receives a binary file (the file isn't complete). We should add an indicator while uploading and the the picture only when the file is totally sent.

### Description

I tried to send a picture via axolotl to another person using android. Despite a few attempts he didn't get anything. On the other way it is possible to receive pictures on axolotl sent by others.

Does anyone have the same problem?
Thanks for helping and for your great work!

Axolotl Version 0.8.1
Ubuntu touch on MX4 (on RC version 73, up to date!)

**Comment by Flaburgan** [comment]
hi flaun, I am able to send pictures to my contact with axolotl. Can you tell us more? Is it a group or a unique person? Is there anything in the logs?

**Comment by flaun** [comment]
Sorry for this late response, was quite busy!
It's to unique person. Haven't tried it so far with groups.
I verified this problem with two different persons.
How can I read out the logs?

Problem still exits on Axolotl 0.8.2

**Comment by flaun** [comment]
Found the solotion.
I quit the app too fast after sending a picture to another person. It looks like there was not enough time for upploiding before closing the app as there is no indicator.

Thanks for your great work!

**Comment by Flaburgan** [comment]
Actually I often have that problem when I am not on a 4G network: I never know if the picture is sent and I can switch off data on my phone. So I'll reopen this, rewording the problem: we need an upload indicator ;)

**Comment by Flaburgan** [comment]
I noticed that the ticks about message sent or not can do the trick. Still, a loading indicator would be great. I'll have a look.

**Comment by Flaburgan** [comment]
![Capture d’écran 2021-01-12 à 23 17 40](https://user-images.githubusercontent.com/930064/104381468-c5c6e380-552c-11eb-8de1-37a26cae5925.png)

Alright, the picture will now have a spinner when the status of the message is pending. See https://github.com/nanu-c/axolotl/pull/310

**Comment by Flaburgan** [comment]
Done in #310
