### ISSUE TITLE
[BUG] Group messages get sent many times

### ISSUE THREAD

**Issue by MoemUT** [nanu-c/axolotl#147]
### Description

Group messages get sent many times

### Steps to Reproduce

1. Join an existing Group
2. Send a message to the Group through Axolotl
3. The message will be sent to each user as many times as there are members in the Group
4. Be hated by your fellow group members for flooding

**Expected behavior:** Message appears in group only once

**Actual behavior:** Message appears in group x times (for a group with x members)
#### Versions

Axolotl Beta 0.8.2

#### Device
Oneplus One (Bacon) running Ubuntu Touch

#### Link to Debug Log
Sorry, no idea how to get this.

**Comment by nanu-c** [comment]
This is resolved now
