### ISSUE TITLE
[BUG] Text is not scrolled down automatically when writing long messages

### ISSUE THREAD

**Issue by Rom4nB** [nanu-c/axolotl#149]
### Description

When writing a message longer than 2 lines, the written text does not scroll down automatically. Only the first two lines are seen and the rest of the message is not seen. Unless backspace is used, then the text scrolls down to the last written line.

### Steps to Reproduce

1. Write a message longer than two lines in a random chat.
2. The touch keyboard covers any line written after the 2nd line. The text is written "blindly".
3. Press backspace: the inserted text scrolls down automatically and finally the last written line is seen.

**Expected behavior:** The text scrolls down automatically while typing and always the currently inserted text is seen.

**Actual behavior:** Keyboard covers any text after 2nd line.

#### Versions

Axolotl Beta 0.8.2
Ubuntu Touch OTA-12 (stable)

#### Device
Fairphone 2

**Comment by Flaburgan** [comment]
Hi @Rom4nB, with the release of OTA-13, a new version of QtWebEngine was provided so Axolotl now runs a much recent chromium engine. Can you please tell us if you still encounter that issue?

**Comment by Flaburgan** [comment]
With https://github.com/nanu-c/axolotl/pull/191 and the refactor of the textarea resize it includes, I have the feeling that this is solved at least for devices running OTA-13 or newer. Closing it, please comment here if you still encounter the problem.
