### ISSUE TITLE
[BUG] Can't see text while writing

### ISSUE THREAD

**Issue by FluorXence** [nanu-c/axolotl#152]
### Description
I can not see what I am typing when writing a text because the the text field is behind the keyboard. 

### Steps to Reproduce
1. Choose conversation
2. Write a text

**Reproduces how often:** [What percentage of the time does it reproduce?]
This occurs all the time I am using axolotl

#### Versions
Axolotl 0.8.2
Ubuntu Touch 16.04

#### Device
PinePhone Community Edition

**Comment by Flaburgan** [comment]
I think that https://github.com/nanu-c/axolotl/pull/133 solved this, as there are no feedback from @FluorXence here I'm closing this issue.
