### ISSUE TITLE
How to Execute?

### ISSUE THREAD

**Issue by straussmaus** [nanu-c/axolotl#156]
### Description

How do I execute this program on Debian with snapd?

### Steps to Reproduce

1. I installed snapd on debian.
2. I installed the axolotl candidate snap.
3. How to Execute?

**Expected behavior:** [What you expect to happen]

I could type "axolotl" or see something in the "sudo snap info axolotl" text, or on the website?

**Actual behavior:** [What actually happens]

I must guess?

#### Versions

0.8.0

> Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`

Can't.

#### Device

Debian 10 with snapd

#### Link to Debug Log
Please provide a link to debug

**Comment by straussmaus** [comment]
@nanu-c Is there other information I should provide?

**Comment by nanu-c** [comment]
Actually if you use gnome there is a desktop file, and then it depends if you want to use only the webserver or electron or qt with webengineview. But actually running `axolotl` should be okay

**Comment by Flaburgan** [comment]
@straussmaus does this answer your question? Can that issue be closed?

**Comment by Flaburgan** [comment]
Closing it, please comment again if you have more questions.
