### ISSUE TITLE
webserver errorlisten

### ISSUE THREAD

**Issue by straussmaus** [nanu-c/axolotl#157]
### Description

Is there supposed to be a webserver?  It doesn't start.

### Steps to Reproduce
Install snapd

1. Install axolotl

2. Nothing happens (see https://github.com/nanu-c/axolotl/issues/156)

3. try `sudo /snap/bin/axolotl`

See this error:

```
INFO[0000] [axolotl] Axolotl server started             
INFO[0000] [axolotl] Starting axolotl ws                
DEBU[0000] [axoltol] axoltol-web path /snap/axolotl/157/bin/axolotl-web/ 
ERRO[0000] [axoltol] webserver errorlisten tcp 127.0.0.1:9080: listen: operation not permitted 
DEBU[0000] [axoltol] axoltol-web path /snap/axolotl/157/bin/axolotl-web/ 
ERRO[0000] [axolotl] webserver error                    
ERRO[0000] [axolotl] webserver error                    
panic: http: multiple registrations for /
```

**Expected behavior:**
I don't know what is supposed to happen.  There is no documentation.

**Actual behavior:** 

See above

#### Versions

> Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`

Can't.

Debian 10
Snapd 2.37
Candidate/Edge (each)

#### Device
Desktop

#### Link to Debug Log
??

**Comment by straussmaus** [comment]
@nanu-c Is there other information I should provide?

**Comment by nanu-c** [comment]
Why is axolotl not allowed to open a port?

**Comment by nanu-c** [comment]
Please open a new issue if you have still the issue.
