### ISSUE TITLE
[BUG] Message for Contacts without signal not really shown

### ISSUE THREAD

**Issue by Naturalbornhippy** [nanu-c/axolotl#161]
### Description

If im importing a contact from the address book, who has no signal (i know that already) and the client is return to the available contacts list, an error message seems to be shown (i see just something yellow blinking)

### Steps to Reproduce

1. Start a new conversion
2. Open Menu 
3. Select new Contacts and than addressbook
4. Select any contact

**Expected behavior:** A Message which is readable should be show, that the user does not have signal or something like this. 

**Actual behavior:** we return and a message blinks for a way to small period of time, i can not read it

#### Versions
Beta 0.8.3
OS Build 2020-W34

#### Device
Nexus LG-D821

**Comment by AA303** [comment]
The same issue exists for Nexus 5, version 0.8.7

**Comment by nanu-c** [comment]
The problem here is, that when you add a number it send all contacts for reverification to the signal server and after a while ~20s-1 minute I get an answer with the actual contact list. It's not possible to have a immediate feedback for 1 number.

**Comment by nanu-c** [comment]
This problem has been addressed. Imported contacts without signal are now greyed out.
