### ISSUE TITLE
[BUG] Avatar Icons looking strange after navigation in settings

### ISSUE THREAD

**Issue by Naturalbornhippy** [nanu-c/axolotl#162]
### Description
I was clicking around in the settings and returned to the main page. the icons looked pretty strange

### Steps to Reproduce

1. Go to Settings
2. Go to the "linked devices" page
3. Leave this setting and return with the back button (two times) to the main page

**Expected behavior:** Everything looks normal

**Actual behavior:** See Screeny

![screenshot20200820_225255995](https://user-images.githubusercontent.com/4314046/90824886-5e6b8580-e338-11ea-8164-ca39983f4e8e.png)

#### Versions
BETA 0.8.3
OS Build 2020-W34

#### Device
Nexus LG-D821

**Comment by AA303** [comment]
I have the same issue on Nexus, version 0.8.7

**Comment by Flaburgan** [comment]
I also reproduce that issue. I'm going to have a look at it.
