### ISSUE TITLE
[BUG] Search in Adding members to a Group is not working

### ISSUE THREAD

**Issue by Naturalbornhippy** [nanu-c/axolotl#163]
### Description
If i want to add users to a work and searching my contact list. If i start typting no contacts are shown

### Steps to Reproduce

1. Go to Main Menu
2. Open Menu and Press New Group
3. Press Add members
4. Open search field
5. Enter a Name

**Expected behavior:** List should be filtered and the names which includes the search text should be shown

**Actual behavior:** If i add the first letter no contacts are shown

#### Versions
BETA 0.8.3
OS Build 2020-W34

#### Device
Nexus LG-D821

#### Link to Debug Log
Please provide a link to debug

**Comment by nanu-c** [comment]
I close this because it's related to groupsv1 that are no longer supported by signal.
