### ISSUE TITLE
[BUG] Contact Names Adds number 1 or 2 at the end

### ISSUE THREAD

**Issue by AA303** [nanu-c/axolotl#168]
### Description

Adding a contact "SSS" will save it as "SSS 1" or "SSS 2"

### Steps to Reproduce

Contacts are saving most of the time correctly. But there are two contacts I have spotted saved as "SSS 1" and "YYY 2"

**Expected behavior:** [What you expect to happen]

When you save a contact as SSS it should appear as "SSS"

**Actual behavior:** [What actually happens]

Not always, but the contact SSS saved as "SSS 1"

#### Versions

0.8.7

Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`

#### Device
What device

#### Link to Debug Log
Please provide a link to debug

**Comment by nanu-c** [comment]
The number behind the contact is added when the contact has 2 numbers, which are both sent to signal for checking if they are using signal. Don't rember why, but maybe it's not working with 2 numbers and the same name

**Comment by nanu-c** [comment]
We cannot have multiple Numbers in 1 account and since renaming is now fixed, i see this as an valid workaround.
