### ISSUE TITLE
[BUG] Desktop Client is missing from Linked Devices

### ISSUE THREAD

**Issue by AA303** [nanu-c/axolotl#173]
### Description

The name of the linked Desktop Client is missing from Axolotl > Settings > Linked Devices

### Steps to Reproduce

1. Link Desktop Client with Axolotl

**Expected behavior:** [What you expect to happen]

The name of the Desktop client should be listed in Axolotl > Settings > Linked Devices

**Actual behavior:** [What actually happens]

The name of the Desktop client is missing from Axolotl > Settings > Linked Devices

#### Versions

0.8.7

Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`

#### Device
Nexus 5

#### Link to Debug Log
Please provide a link to debug

**Comment by Danfro** [comment]
Actually it is there (here anyway). BUT you need to leave the page and return. [Just wanted to report that] Somehow the view does seem to not refresh properly.

**Comment by Flaburgan** [comment]
Fixed by https://github.com/nanu-c/axolotl/pull/223, closing.

**Comment by AA303** [comment]
Thanks!
