### ISSUE TITLE
[BUG] - Editing contact name, creates a duplicate instead

### ISSUE THREAD

**Issue by AA303** [nanu-c/axolotl#176]
### Description

When you edit a contact name and save the change. This action will update name of the contact and create a duplicate contact with exactly the same name.

### Steps to Reproduce

1. Go to Axolotl > Chat List > click "Pen/New Message" icon
2. Press and hold on contact name to edit, Click "Edit/Pencil" icon
3. Enter new contact name and save

**Expected behavior:** [What you expect to happen]

Contact name should be update without creating a duplicate contact

**Actual behavior:** [What actually happens]

Contact name gets updated and created a duplicate contact with the new name.

#### Versions

0.8.7

Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`

#### Device
Nexus 5

#### Link to Debug Log
Please provide a link to debug

**Comment by nanu-c** [comment]
closed in https://github.com/nanu-c/axolotl/pull/757
