### ISSUE TITLE
[BUG] taruti/mimemagic 404: Not Found

### ISSUE THREAD

**Issue by olof-nord** [nanu-c/axolotl#178]
### Description

Building axolotl fails, as it cannot download all required dependencies.

### Steps to Reproduce

1. clone repository
2. go clean
3. env GOOS=linux GOARCH=arm64 go build -o build/linux-arm64/axolotl .

**Expected behavior:** 
Build does not fail

**Actual behavior:** 

```log
$ go clean
go: bitbucket.org/taruti/mimemagic@v0.0.0-20120314151349-e5179c80a024: reading https://api.bitbucket.org/2.0/repositories/taruti/mimemagic?fields=scm: 404 Not Found
```

```log
$ env GOOS=linux GOARCH=arm64 go build -o build/linux-arm64/axolotl .
go: bitbucket.org/taruti/mimemagic@v0.0.0-20120314151349-e5179c80a024: reading https://api.bitbucket.org/2.0/repositories/taruti/mimemagic?fields=scm: 404 Not Found
```

#### Versions

latest version from `main` branch.

#### Device
PinePhone running mobian and phosh

```
$ go version
go version go1.15.2 linux/arm64
```

#### Link to Debug Log
Provided above

**Comment by olof-nord** [comment]
The dependency is not accessible anymore (?):
https://bitbucket.org/taruti/mimemagic

**Comment by olof-nord** [comment]
This dependency was unfortunately brought back with c37b8510cdf6f1bc12afad3a0ded3d17022b8676.

Is this repository available for you, @nanu-c?
https://bitbucket.org/taruti/mimemagic

**Comment by nanu-c** [comment]
This was by accident it should import this https://github.com/signal-golang/mimemagic
