### ISSUE TITLE
axolotl-web: Provide information which node.js version is supported/should be used

### ISSUE THREAD

**Issue by olof-nord** [nanu-c/axolotl#180]
**Is your feature request related to a problem? Please describe.**
Which node version(s) are supported by axolotl-web?

**Describe the solution you'd like**
Possibly the addition of a [.nvmrc](https://github.com/nvm-sh/nvm#nvmrc) file which specifies the expected Node version

**Describe alternatives you've considered**
The Node version could also be specified in a readme file.

**Comment by nanu-c** [comment]
Vue CLI 4.x requires Node.js version 8.9 or above (v10+ recommended). So it's that npm is only used for building vuejs, so on whichever version vuejs is depending on.

**Comment by nanu-c** [comment]
But I can add a .nvmrc, however I never used nvm

**Comment by olof-nord** [comment]
Thanks for your reply!

NVM is short for Node Version Manager, its a wrapper which lets you easily use different node versions at the same time without hassle. By using `nvm use` it picks up and sets the node version specified.

I read the Vue.js [Installation](https://cli.vuejs.org/guide/installation.html) and I agree that specifying a minimum version of Node.js 10+ somewhere would be good. To say v10+ is a good first step.

When developing locally, I think it would be beneficial, if not needed, to use the exact same version as to not run into bugs just because person A uses v10.0 and person B uses v14. After all, node v10 was released in 2018, v14 in April this year.
Later at a point when a build pipeline is in place, the exact version to use also comes to question.

What about starting to pin down the Node version you are using, or the versions you know works?

With the .nvmrc file it is possible to specify "lts/*" - with this the latest, actively supported Node version is specified. That is currently "erbium", which is as of today `v12.18.3`. One idea would be to use this.

**Comment by olof-nord** [comment]
I see that when packaging axolotl-web with snap, node `v12.13.1` [is specified](https://github.com/nanu-c/axolotl/blob/main/snap/snapcraft.yaml#L36). If that is the node version used when publishing, that is the version to use when developing locally. 

A topic for a future discussion might be when/if the Node version used when publishing with snap should be adjusted to the latest, actively supported Node version (currently v12.13.x -> v12.18.x) as to not publish with outdated dependencies.
