### ISSUE TITLE
[BUG] Can't fetch github.com/Sirupsen/logrus

### ISSUE THREAD

**Issue by duncan-bayne** [nanu-c/axolotl#186]
### Description

Can't fetch github.com/Sirupsen/logrus when setting up Pinephone dev environment.

### Steps to Reproduce

1. go get -d ...

**Expected behavior:** [What you expect to happen]

I expect all dependencies to be fetched.

**Actual behavior:** [What actually happens]

```
go: github.com/tmc/grpc-websocket-proxy/examples/cmd/wsechoserver imports
        github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.6.0: parsing go.mod:
        module declares its path as: github.com/sirupsen/logrus
                but was required as: github.com/Sirupsen/logrus
```

#### Versions

Git sha `217ae65fc4b5246ad93760638fc125cdfca3287f`.

#### Device

Pinephone Braveheart, running Mobian Sid nightly.

**Comment by nanu-c** [comment]
Can you try to run `go run .` instead of `go get -d ...` ? This happens in a dependency of a dependency of a dependency  that haven't updated their dependencies

**Comment by duncan-bayne** [comment]
That worked - status is now:

`astikit: worker is now waiting...`

**Comment by nanu-c** [comment]
In golang 1.15 we have to use `go mod download` instead of `go get -d ...`.
`astikit: worker is now waiting...` means, it's downloading chromium

**Comment by nanu-c** [comment]
With `go mod download`/ golang 1.15 it works on current main branch, so i will close this
