### ISSUE TITLE
[BUG] sending the first message needs pressing the send button twice

### ISSUE THREAD

**Issue by Danfro** [nanu-c/axolotl#189]
### Description

When writing a multiline message, after pressing the send button the message is not send. The message collapses to single line. Only after pressing the send button again the message is send.

### Steps to Reproduce

1. write multiline message
2. press send

**Expected behavior:** message is send

**Actual behavior:** message is not send but only reduced to single line.

A single line text does get send right after pressing the send button the first time.

#### Versions

Version 0.8.7

#### Device
Xperia X devel channel

Log: http://paste.ubuntu.com/p/RCKV8qvFsZ/

**Comment by Flaburgan** [comment]
Yeah my refactor of the front-end caused that regression. Now that OTA-13 is released and with it the new QtWebEngine is available for every UT users, I'm going to resume my work on the layout.

**Comment by Flaburgan** [comment]
Good news, I reproduce this issue on desktop, so I should be able to fix it pretty quickly.

**Comment by Danfro** [comment]
Cool. I know we talked about that some time ago. But I did not remember if I promised to make a bug report about it. ;-)
Can't hurt anyway for tracking things.

Good news if you know where this might be coming from.
