### ISSUE TITLE
Clarify purpose of libs/libsignal-protocol-c git submodule

### ISSUE THREAD

**Issue by olof-nord** [nanu-c/axolotl#193]
**Is your feature request related to a problem? Please describe.**
Where and for what purpose is the libs/libsignal-protocol-c git submodule used?

**Describe the solution you'd like**
I cannot find any usage of it. If it is no longer used or needed, I propose to delete it.

**Describe alternatives you've considered**
Alternate solution: Provide documentation how and where it is used.

**Additional context**
The git modules file can be found here: [.gitmodules](https://github.com/nanu-c/axolotl/blob/main/.gitmodules)

**Comment by olof-nord** [comment]
If this is a needed part, I suggest to manage it as a go dependency, as to allow for a versioning which aligns with the rest of the backend dependencies and follows the same patterns.

**Comment by nanu-c** [comment]
We don't need this anymore. Or better this is a general question. At the moment we maintain a reimplementation of all what signal form ows does in [signal-golang/textsecure](https://github.com/signal-golang/textsecure). This lib also gives some of the core functionalities like the basic encryption. Upside of this is, it's maintained by ows, downside is, it lacks a lot  and it's somehow behind the java pendant. So i would say, remove it.

**Comment by olof-nord** [comment]
Thanks for the explanation! OWS -> Open Whisper Systems, right?

I would also vote for the removal of the git submodule for now then.

**Comment by Flaburgan** [comment]
I'm still a bit afraid about us maintaining something as critical as the Signal protocol implementation, but to include C code probably is too much work at the moment so let's remove it. Is this something which can be included in a bugfix release and I tag it 0.8.8?
