### ISSUE TITLE
[BUG] Only the first picture is shown several time on a message received with multiple pictures

### ISSUE THREAD

**Issue by Flaburgan** [nanu-c/axolotl#197]
![image](https://user-images.githubusercontent.com/930064/94477157-caf86080-01d1-11eb-8563-16ddb6d058cb.png)

I'll check that problem.

**Comment by Flaburgan** [comment]
@nanu-c it looks like the problem here is in the Go code, not in the front-end part, so I let this one to you ;)

**Comment by nanu-c** [comment]
Only happens, when the message was sent from a signal client on android

**Comment by Flaburgan** [comment]
>Only happens, when the message was sent from a signal client on android

I don't think so. My girlfriend just sent me many pictures with her phone and I had the bug.
