### ISSUE TITLE
Appimage package

### ISSUE THREAD

**Issue by Thatoo** [nanu-c/axolotl#202]
**Is your feature request related to a problem? Please describe.**
Easy installation on distributions that don't come with Snap or Ubuntu Touch store installed without forcing user to install flatpack.

**Describe the solution you'd like**
An appimage package we can download from github or https://axolotl.chat/download/axolotl.appimage and run just after a double click.

**Describe alternatives you've considered**
Only real alternative right now would be to compile the build or install snap or soon install flatpack... on top of deb or rpm....

**Additional context**
Appimage can be used on all linux system just after downloading it without any need to install any package manager like flatpack or snap.

**Comment by Flaburgan** [comment]
Hello @Thatoo, and thanks for your interest about Axolotl.
Do you have any knowledge about how to build an AppImage? If yes, are you willing to have a look? It would be nice to have Axolotl available as an AppImage but I don't know how to do that and have other features I want to work on.

**Comment by Thatoo** [comment]
Unfortunately I don't have this knowledge. I understand this feature would not get the priority from main dev of the project but I thought it would be nice to track it somewhere.
Hopefully someone with more knowledge than me on appimage will pass by.
I just love the easiness of appimage.

**Comment by olof-nord** [comment]
Hello @Thatoo, please see MR #237 and see if it does the trick for you.
If you need any further help, just write here.

**Comment by Thatoo** [comment]
Thank you. I'll wait for the MR to be merged and I'll test it asap

**Comment by Thatoo** [comment]
I couldn't find the appimage when v0.9.0 got released.

**Comment by Thatoo** [comment]
I saw the MR @olof-nord but I'm sorry, I didn't get where can the AppImage for 64-bit Intel CPUs be downloaded?
On AppImagHub, https://appimage.github.io/, they ask me for the URL to download it in order to add Axolotl to AppImageHub.

**Comment by Thatoo** [comment]
https://github.com/AppImage/appimage.github.io/issues/2419#issuecomment-750433134

**Comment by Flaburgan** [comment]
@Thatoo I did the release of the 0.9.2 version and I only published the clicks (for Ubuntu Touch) attached to the release tag on github. I just added the [x64 binary for Linux](https://github.com/nanu-c/axolotl/releases/download/v0.9.2/axolotl.linux.x64), in case this is useful for you. I don't know how to do the AppImage push so you'll have to wait for Olof or @nanu-c here sorry.

**Comment by olof-nord** [comment]
The Axolotl CI pipeline actually builds an AppImage for each commit: however I believe it is only visible to maintainers of the repo (@nanu-c and possibly others?). The AppImage is built with the CI architecture, and as a result is for x86_64.

It might be worth talking about what options we should offer for releases - then add a way to automate this a s far as possible.

Re: AppImage, if you want a x64 option, it is more or less done. If we also want to support other architectures (I think of arm directly), we could get in touch with @rathboma as he was offering a GitHub CI worker running arm in the https://github.com/signalapp/Signal-Desktop/issues/3410#issuecomment-692724499 thread.

**Comment by nanu-c** [comment]
Could it be possible to add the appimage automagically to the release with https://github.com/marketplace/actions/github-upload-release-artifacts ?

**Comment by Thatoo** [comment]
Yessss, the appimageis available on version 0.9.3. Thank you!
