### ISSUE TITLE
[BUG] Axolotl front isn't able to connect to UT back anymore

### ISSUE THREAD

**Issue by Flaburgan** [nanu-c/axolotl#216]
Steps to reproduce:
1. Start Axolotl on your phone connected with WiFi. Its IP is 192.168.1.11
2. Start `VUE_APP_WS_ADDRESS=192.168.1.11 npm run serve` on the computer
3. Open `localhost:8080` in Firefox
4. See in the console that Firefox isn't able to connect to the phone backend

**Comment by nanu-c** [comment]
We have a new comand line parameter:

-  `-host` Set the host to run the webserver from. Defaults to localhost.
In the desktop file the `-host` hast to be set to 0.0.0.0 in `click/textsecure.desktop` and voila it works again

**Comment by Flaburgan** [comment]
Interesting. What is that `textsecure.desktop` file? Can we always add this flag in the version we publish or should this only be for development as it is a security issue?

**Comment by Flaburgan** [comment]
indeed, building the click with `Exec=textsecure -e ut -host 0.0.0.0 %u` allows me to connect from my computer again. Thank you!
