### ISSUE TITLE
Unable to register (Your registration is faulty)

### ISSUE THREAD

**Issue by wayneoutthere** [nanu-c/axolotl#217]
### Description

When trying to register / request code, process fails with 

### Steps to Reproduce

1. Open app for first time
2. Proceed to 'Connect with Signal' screen
3. Enter number (Canada in my example)
4. Long pause followed by "Error - Your Registration is faulty.  Please consider to register again"

**Expected behavior:** 
I expected code to be sent and registration to complete

**Actual behavior:**
See above in steps

#### Versions

Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`
Can't find this....

Ubuntu Volla phone
OS Ubuntu 16.04 

OS Build number 2020-09-28/2

Channel is Development if that helps

#### Device
Volla

#### Link to Debug Log
Please provide a link to debug
sorry can't figure this out :(

**Comment by nanu-c** [comment]
Can you sent me a volla phone ut, then i will solve it :)
But you can also send me the log with logviewer. The error happens for example if you registered signal android and if you used a code on that. Before using the number again you have to deregister the previous session.

**Comment by wayneoutthere** [comment]
they are [hiring now ](https://volla.online/blog/files/october-jobs.html) so likely they will equip you if you take the job (do it!)

I'll try to find time to loggit but not likely today sorry. promise to do my best

**Comment by Flaburgan** [comment]
@wayneoutthere you can use the `logviewer` app which allows you to access the log and directly submit it to paste.ubuntu.com with one click, and then paste it here.

**Comment by LongJohn-Silver** [comment]
I get this message when trying to register (although I have an account already) and it asks me my PIN.

**Comment by LongJohn-Silver** [comment]
I deactivate the PIN registration, tried it again and I received the same error.

**Comment by baarkerlounger** [comment]
I've got the same `Your registration is faulty .Please consider to register again` and the error message in the terminal is:

```
ERRO [axolotl] error: Need to solve captcha
ERRO [axolotl] error: websocket: bad handshake
```

Looks like there's some rate limiting server side that Axolotl doesn't implement.

**Comment by Blackoverflow** [comment]
According to https://www.reddit.com/r/signal/wiki/faq#wiki_why_was_i_asked_to_complete_a_google_captcha_during_registration.3F, the captcha is only needed if the registration is from a network that is deemed untrustworthy by signal.

I suggest to retry the registration from another network/WiFi.

**Comment by baarkerlounger** [comment]
Can confirm that in my case switching off the wifi on my phone and registering using my 4G connection succeeded.

**Comment by Spraltik** [comment]
I am getting the same message since the latest update 0.9.0.1. Was fine on 0.9.0. It comes sporadically after a day or two even after unregistering and registering again. Wifi or 4G seems to make no difference. I am on the latest UBports version on a Aquarius E4.5.

**Comment by Flaburgan** [comment]
@Spraltik this message is generic to say we have problems with Signal server. If you have it for time to time, it's not the same issue. Please check the logs and open a new one.

**Comment by Flaburgan** [comment]
Okay, I just tried to register myself with a +44 number I used to use to develop on Axolotl, and from my home ADSL connection in France (so a trustworthy one, I'm using it daily with Signal desktop), I also had this message. Here is the complete log:

```
INFO[2021/02/04 22:41:08] [textsecure] request verification code for  +4477XXXXXX
DEBU[2021/02/04 22:41:09] [textsecure] GET /v1/accounts/sms/code/+4477XXXXXX?client=android 402 
DEBU[2021/02/04 22:41:09] &{0x72ce90 0xc000488080 0x73ce80}            
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 402 Payment Required</title>
</head>
<body><h2>HTTP ERROR 402 Payment Required</h2>
<table>
<tr><th>URI:</th><td>/v1/accounts/sms/code/+4477XXXXXXXX</td></tr>
<tr><th>STATUS:</th><td>402</td></tr>
<tr><th>MESSAGE:</th><td>Payment Required</td></tr>
<tr><th>SERVLET:</th><td>io.dropwizard.jersey.setup.JerseyServletContainer-7c6ab057</td></tr>
</table>

</body>
</html>
ERRO[2021/02/04 22:41:09] [axolotl] error:  Need to solve captcha      
DEBU[2021/02/04 22:41:09] [textsecure] Websocket Connecting to signal-server 
ERRO[2021/02/04 22:41:10] websocket: bad handshake                     
DEBU[2021/02/04 22:41:10] [axolotl-ws] error: websocket: bad handshake 
ERRO[2021/02/04 22:41:10] [axolotl] error:  websocket: bad handshake   
ERRO[2021/02/04 22:41:13] [axolotl] error:  Your registration is faulty
```

I'm starting to think that the "v1" thing here is the problem...

**Comment by Flaburgan** [comment]
Apparently the registration flow changed at the end of 2017 @nanu-c : https://github.com/signalapp/Signal-Android/commit/90ff0e58b0206ac2b047c3db70980f29a533b9d9 do you think that like contact discovery, we missed a change and they cut the old way to register?

If really the needed fix is the captcha implementation, then they did it there: https://github.com/signalapp/Signal-Android/commit/02b0800b22e2faaa1f659d34ac3bb2f44eda3631

**Comment by Flaburgan** [comment]
@wayneoutthere now Axolotl allows you to fill the captcha, can you confirm that you're able to register now?

**Comment by wayneoutthere** [comment]
I can fill in the captcha now, this is working. However, after I get past that it sends the code to me, but, the cursor gets stuck on the last number in the code and will not allow me to submit the SMS verification code (it gets stuck)

**Comment by wayneoutthere** [comment]
oh........... man.  I didn't realize the 'send code' button under the __ __ __ - ___ ___ ___ was required.  I thought it was part of pre-captcha process.  I think in all the other apps, after you enter the last digit it automatically submits it.... perhaps I'm not smart but that didn't feel intuitive...  i seem registered now thanks

**Comment by nuehm-arno** [comment]
The issue seems resolved.
