### ISSUE TITLE
How to use axolotl on pinephone?

### ISSUE THREAD

**Issue by quixote7** [nanu-c/axolotl#230]
I installed axolotl on ubports on pinephone. I get a screen prompting me to enter a phone number.  Which number? Of the sim card in the phone? Of a number I'm trying to reach? Whatever I input, it doesn't go anywhere. What do I need to do? Or doesn't it work on pinephone? Thanks in advance

**Comment by nanu-c** [comment]
Axolotl is a fully fledged Signal client. That means you have to enter your phone number, then it sends a sms to that phone number. Registration without a phone number is not possible. Registration also needs a internet connection and on ubuntu touch a deactivated add blocker.
If you entered a valid phone number and it's still not sending a sms or going to  the next page asking for the pin, then you are very welcome to attach your logfile.

**Comment by quixote7** [comment]
:redface: It's been some two years since I put Signal on my other phone and I forgot about the registration step. Just during the install for the purpose of testing some of the functions, I have a foreign sim in the pinephone. I'm sure I've entered the local phone for registration incorrectly. Thanks for answering my super-d.u.m.b so quickly!

(Not likely in the linux community, but if this moves to wider application, I may not be the only one who gets confused at that step. It might be worth changing the prompt to "Enter valid phone number to register axolotl"? Or something like that?)

**Comment by Flaburgan** [comment]
The UX of the registration definitely needs love. I will take care of it in the coming weeks (I hope). Thank you for checking it again.
