### ISSUE TITLE
Flatpak crashes on Mobian (Pinephone, aarch64)

### ISSUE THREAD

**Issue by joshbowyer** [nanu-c/axolotl#250]
Commented on another issue (it was the MR for the Flatpak image), creating a new issue for it here:

Installing the Flatpak on Mobian works without issue, but can't launch the app. Electron crashes right after Axolotl attempts to create the getPhoneNumber dialog, and the exit code is 7. However, if I provide full permissions to /home via Flatseal, the exit code changes to -1.

The other commenter mentioned there is an issue with electron but I have not seen any documentation anywhere on this. Also, which qml packages would be required to run with `axolotl -e ut` ?

**Comment by nanu-c** [comment]
`axolotl -e ut` needs `qmlscene` to be installed, what happens if you run that command? Actually we can add smth. like `-e mobian` because the dependencies of `axolotl -e ut` are only for system integrations.

**Comment by joshbowyer** [comment]
That sounds like a good idea, I think maybe adding a dependency for notifications on Mobian would be necessary too? I'm trying to get an answer as to which packages would be required but it would probably be a DBus thing

**Comment by joshbowyer** [comment]
Looks like it just uses the freedesktop notification api

**Comment by nanu-c** [comment]
> Looks like it just uses the freedesktop notification api

That already works :)

**Comment by joshbowyer** [comment]
Should a new issue be created for the `-e mobian` change?

**Comment by Djhg2000** [comment]
I think the name should be a little more generic than `mobian` since Mobian aims to eventually reintegrate into Debian. Perhaps `debian` would serve as an acceptable substitute?
