### ISSUE TITLE
Add "mobian" switch

### ISSUE THREAD

**Issue by joshbowyer** [nanu-c/axolotl#253]
Per #250 , a new env switch should be added to run with qmlscene like in UT but without the system integrations. This should be invoked by passing `-e mobian` to bin/axolotl

**Comment by Djhg2000** [comment]
I think the name should be a little more generic than `mobian` since Mobian aims to eventually reintegrate into Debian. Perhaps `debian` would serve as an acceptable substitute?

**Comment by nanu-c** [comment]
maybe, maybe not, because snaps are working on ubuntu which is based on debian. My pinephone is on the way and then i need to check the general problem because either flatpack or snap are failing.

**Comment by ragreenburg** [comment]
Any update on how long this might take?

**Comment by joshbowyer** [comment]
Sounds that that's currently dependant on the mail courier lol

**Comment by Blackoverflow** [comment]
How about "qml" as name for this option?
I think a option named after a platform is only right if that option contains platform specific integration.

**Comment by duncan-bayne** [comment]
>  I think a option named after a platform is only right if that option contains platform specific integration.

This, a million times this!  In general, detect or specify features, not platforms.  Doing it the other way around leads to all sorts of problems when introducing a new platform with a mix of existing and new features; witness the bazillion-line patches needed to port Electron to FreeBSD.

**Comment by joshbowyer** [comment]
How simple or complex would adding the `-e qml` switch be? Also did you receive your Pinephone?

**Comment by nanu-c** [comment]
Can you try?
On Mobian followed this:
```
sudo apt install golang nodejs npm mercurial python qmlscene
 go get -d github.com/nanu-c/axolotl
 cd $(go env GOPATH)/src/github.com/nanu-c/axolotl
 go mod download

 cd axolotl-web
 # npm sass does not support arm64 so we need to rebuild it
 npm rebuild node-sass
 npm install
 npm run build

 cd ..
 mkdir -p build/linux-arm64/axolotl-web
 env GOOS=linux GOARCH=arm64 go build -o build/linux-arm64/axolotl .
 cp axolotl-web/dist build/linux-arm64/axolotl-web -r
```
And then had to delete everything in rm -rf /home/mobian/.config/textsecure.nanuc and run the last two steps again

**Comment by joshbowyer** [comment]
This returns the exact same issue as before: `ERRO[0001] '/home/mobian/.config/textsecure.nanuc/electron/vendor/electron-linux-arm64/electron' exited with code: 7`

I dont know how much work would be involved in adding `-e qml` as an option but that would be more ideal than trying to "fix" electron anyway (too much overhead and theyre just gonna break it again anyway most likely)

**Comment by nanu-c** [comment]
Now the first good question, which mobian are you using? Next thing mobian uses Gnome aka gtk. On my shiny pinephone i had to install qmlscene to run a qml only app. Axolotl doesn't include any gtk/qt bindings at the moment. So lets see what works best with go.

**Comment by joshbowyer** [comment]
What mobian? What do you mean, there is only one?
