### ISSUE TITLE
[BUG] No link to Signal Desktop with pinephone/mobian

### ISSUE THREAD

**Issue by nuehm-arno** [nanu-c/axolotl#258]
### Description
Hello there,
following the installation guide from the mobian wiki including some tweaks, I managed to start and register Axolotl on my Pinephone/Mobian. But linking Signal Desktop (Arch Linux) to Axolotl is not working.

### Steps to Reproduce
Extract the uuid/key-string from the Signal Desktop qr-code with qtqr and copy it into the "desktopLink" box.

**Expected behavior:**
Signal Desktop is linked to Axolotl.

**Actual behavior:**
The box closes without adding Signal Desktop as a second devices.

Do I have to alter the uuid/key-string in some special way that I'm not aware of?

#### Versions
Axolotl 0.8.9
With option "-e server" and Gnome Web as UI (http://127.0.0.1:9080); Midori is working, too.

#### Device
Pinephone/Mobian (latest updates)

Edit: Added more informations.

**Comment by nanu-c** [comment]
After entering the  uuid/key-string signal desktop asks you to confirm the registration. Did you do that?

**Comment by nuehm-arno** [comment]
Unfortunately, Signal Desktop is only showing the qr-code.<br>With signal-cli, for example, the linking process works like a charm.

**Comment by nuehm-arno** [comment]
With the latest updates of Mobian and using Firefox aus UI, the linking process worked!

Closing the issue...

**Comment by gurucubano** [comment]
> Unfortunately, Signal Desktop is only showing the qr-code.
> With signal-cli, for example, the linking process works like a charm.

I have installed `signal-cli` in my FreeBSD-13 CURRENT laptop. When I try to make a 'link' to use this with the `axolotl` in my Ubuntu BQ E4.5 mobile as a second device, it generates the URI and then it hangs and times out:
```
$ signal-cli  link -n freebsd-cli
tsdevice:/?uuid=dCLeTldDe-C79Z3GP89Vsg&pub_key=Be7gi8xrEn2XowTtXou8uLQgebSHb4toUEyKu5cdEqtP
Link request timed out, please try again.
```
When I now use the QR code generated from the above URI in `axolotl`, nothing happens after entering (paste) the URI, it just jumps back to the page with the `+` sign. Do I something wrong?

What I want to achieve is sending messages with the `signal-cli` as they would have been sent from the mobile device with `axolotl`. Or is this understanding wrong?

**Comment by Flaburgan** [comment]
Signal has two types of clients: Primary and secondary. The primary clients allow you to register on Signal and manage your contacts etc. It is the one which handles your private key and you can have only one. Axolotl is a primary client, like the Android and iOS applications. Then there are secondary clients, for example the Desktop client. You can have as much secondary clients installed as you want. You need to link each installations to your primary client, for it to get your private keys and be able to talk.
signal-cli is, as far as I know (I never used it) a primary client, so you can't use it along Axolotl. Maybe there is a way to turn it into a secondary client, but then you should ask on signal-cli repository, I can't help you here. My advice would be to install the official desktop client on your BSD machine, although I don't know if this is supported.

**Comment by gurucubano** [comment]
With the help in the signal-cli Git repository I got to learn, that one must create and provide the URI (via QR code) to the app `axolotl` while `signal-cli` is still running. The it associates fine and it works now, `signal-cli` as the secondary client of `axolotl`.
