### ISSUE TITLE
Pinephone: Wont run on ArchARM [BUG]

### ISSUE THREAD

**Issue by GameyLP** [nanu-c/axolotl#264]
### Description

It wasn't really fun but I got Axolotl to install on ArchARM with Phosh. Now the issue, when I try to start Axolotl I get the following error and I don't have the knowledge to fix it myself:
``webserver errorlisten tcp 127.0.0.1:9080: bind: address already in use``

I just thought maybe someone has any idea how to solve it :D

**Comment by NeroBurner** [comment]
please provide your solution for future reference
