### ISSUE TITLE
Show messages written on Signal Desktop in Axolotl

### ISSUE THREAD

**Issue by Rom4nB** [nanu-c/axolotl#268]
**Is your feature request related to a problem? Please describe.**
When I write messages on Signal Desktop, they are unfortunately not shown in Axolotl. The other way round it works: when I write in Axolotl, the message appears also in Signal desktop. 

**Describe the solution you'd like**
It would be nice when messages written on the Desktop would also show up in Axolotl. The message history in Axolotl gets very confusing otherwise ...

**Describe alternatives you've considered**
Alternative would only be to install Signal on an Android device and let Signal on UT/Axolotl run as "Connected Device". But this would probably need a new app?

**Comment by nanu-c** [comment]
Lucky you, it already has been fixed in https://github.com/nanu-c/axolotl/pull/254 :)
