### ISSUE TITLE
deb package and repo

### ISSUE THREAD

**Issue by alien2003** [nanu-c/axolotl#298]
I have Cosmo Communicator with Gemian (Debian from Planet Computers) and I want to be able to use Signal on it.

It would be great to have APT repository for Debian users

Flatpak repository would also be a thing as well as self-updating AppImage

**Comment by nuehm-arno** [comment]
If the Cosmo Communicator is an arm64 device, you can use this deb-file
https://github.com/nuehm-arno/axolotl-mobian-package

If not, try the current flatpak installation procedure
https://github.com/nanu-c/axolotl/blob/main/docs/INSTALL.md#flatpak

And please consider closing this issue.
