### ISSUE TITLE
Documentation needed: registration

### ISSUE THREAD

**Issue by seteahconnoc** [nanu-c/axolotl#316]
Problem: I am not registered.
Solution: I want to use axolotl.
Alternatives: ?
Additionial context: Starting axolotl on my debian system or on my UBports phone doesn't lead me to anything. I guess, I have to do a registration at first. A kind of Wiki entry on how to register without an Android and/or iPhone would be nice.

Please, keep in mind that this is a confused newbie speaking. Feel free to ask for further information on this issue.

**Comment by Flaburgan** [comment]
Axolotl should allow you to register, can you please add a screenshot?

**Comment by seteahconnoc** [comment]
@Flaburgan Thank you for your quick responce. In order to get a screenshot, I checked out the functionality again. Luckily, the registration process seems to work just fine now. Obviously, it had to initialize (in some way). As I said: "confused newbie" - Anyway: Thank you.

**Comment by Flaburgan** [comment]
The Signal servers were overloaded yesterday, you are probably not the one to blame ;)
