### ISSUE TITLE
[BUG] All messages & contacts gone after "Your registration is faulty. Please consider to register again." 

### ISSUE THREAD

**Issue by GerryT11** [nanu-c/axolotl#317]
### Description

Today, Axolotl showed the error message: "Your registration is faulty. Please consider to register again."
I clicked on the option of this error message to unregister and the registered again.

-> Now all old messages / chat history and contacts are gone! Can you help me how I can retrieve/show these again? Thank you very much!

Some more information:
I have a manual back-up of the textsecure.nanuc files via ADB from end of December and just made a new one (after the re-registration). The files seem to be on the device, but don't show up.

P.S. I have added the same question in the UBPorts forum: https://forums.ubports.com/topic/5485/axolotl-all-messages-contacts-gone-after-your-registration-is-faulty-please-consider-to-register-again

#### Versions
Axolotl v0.9.4 (when the error message showed up, it was still v0.9.3)

#### Device
Volla Phone

#### Idea
Is it maybe possible to copy the old registration/key files from the old December back-up on the device? The idea would be to copy over the files from the back-up files of the folder "local/share/.storage/identity", or anything similar. Do you think this could work to get back to the situation before re-registration?

**Comment by Flaburgan** [comment]
Signal servers were overloaded this afternoon, situation is back to normal now. However, the message is misleading, maybe we can keep that issue open to reword it.

**Comment by GerryT11** [comment]
SOLVED. This worked for me:

I did some experimentation how to get my old messages and contacts back. Here is the solution, which works (with a little draw-back):

    I used the new re-registered Axolotl profile (all files in .config/textsecure.nanuc and .local/share/textsecure.nanuc) as basis.
    Then I replaced the database db.sql file with the old db.sql from my December back-up. (Apparently, Axolotl deletes all old messages from the db.sql after re-registration. On the other hand, attachments remain in the profile).
    Then I copied the contacts.yml from the back-up to the config folder of the new profile.

This works fine, I see all my messages and all contacts. The only draw-back is that I can only write a message to a contact AFTER this contact has written a new message to me. Apparently, the other person has to re-initiate the secure connection. I can live with this draw-back, as it is a matter of time that all (relevant) contacts will be working again.

**Comment by nanu-c** [comment]
>I can only write a message to a contact AFTER this contact has written a new message to me. Apparently, the other person has to re-initiate the secure connection. I can live with this draw-back, as it is a matter of time that all (relevant) contacts will be working again. 

That's the general situation now on axolotl because contact discovery changed it's way how it works.

**Comment by nanu-c** [comment]
https://signal.org/blog/private-contact-discovery/

**Comment by Flaburgan** [comment]
I reworded the popup to avoid user to unregister. I'm closing this issue.
