### ISSUE TITLE
Desktop client provisioning/syncing partially

### ISSUE THREAD

**Issue by seteahconnoc** [nanu-c/axolotl#318]
Problem: I am trying to use the same signal registration from my UBports device and from my Debian desktop. If I am using the same phone number, I get this message: "Your registration is faulty. Please consider to register again."

Solution: Syncing.

Alternatives: ?

Additional context: As a newbie, I am discovering axolotl. Thanks for your work. Right now, I am able to register for one phone number only from one device at a time. The feature "connected devices" (in german: "Verknüpfte Geräte") on my UBports device in waiting for a QR code from my Debian device at this moment. Where do I find it? Sadly, the only option seems to be a registration, which leads to the described problem.

**Comment by Flaburgan** [comment]
Hello! The way Signal protocol works, you need to have only one primary client where you register (which would be your Axolotl on Ubuntu touch) and the client on other devices are secondary clients. Those need to be linked to the primary client. On debian, please install the official Signal desktop client, then go to the settings of axolotl in UT and scan the qr code of the desktop client to link them.

**Comment by seteahconnoc** [comment]
@Flaburgan Thank you. Excuse me, but I still don't get it.

(1.) I install axolotl on my UBports phone.
(2.) I register on my UBports phone.
(3.) I install signal on my Debian notebook. There is a QR code.
(4.) I go to the settings of axolotl on UT. I connect both instances via QR code. I get an confirmation on my phone.
(5.) Using signal on my Debian device, I see my phone number.

So far, so good. - But I want to use axolotl on my Debian device. How do I tell axolotl on Debian to connect to UT? Do I have to copy a line from the configuration files of signal on Debian to axolotl on Debian? Is this done automatically? ... Any help on this would be welcome.

**Comment by Flaburgan** [comment]
>But I want to use axolotl on my Debian device

You can't (and shouldn't) do that. Axolotl can't be a secondary client, and is way less complete that the official Signal client. Why do you want to use Axolotl on debian?

**Comment by seteahconnoc** [comment]
@Flaburgan I was trying to use Axolotl on debian, just because it's there / just for fun. Thank you the information that it cant't be a secondary client.
