### ISSUE TITLE
How to start a video chat?

### ISSUE THREAD

**Issue by CesarHerreraG** [nanu-c/axolotl#320]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CesarHerreraG** [comment]
I can write text but don't know use video.

**Comment by nanu-c** [comment]
it's currently not possible, because ubuntu touch doesn't support media streaming. No access to mic and video in the qt webengineview except 1 or 2 device models. Until that's not solved it doesn't make sense to spend time on it

**Comment by CesarHerreraG** [comment]
Ok
