### ISSUE TITLE
Some messages sent with the desktop client are displayed in the wrong conversation in Axolotl

### ISSUE THREAD

**Issue by Flaburgan** [nanu-c/axolotl#326]
I'm not sure how I put myself in this state, but some message I am sending to a contact with the desktop client (and which are correctly received by this contact) are displayed in another contact conversation in Axolotl!

The logs aren't really useful:
```
DEBU[2021/01/24 14:17:09] [textsecure] SyncMessage recieved at 1611494226241 
DEBU[2021/01/24 14:17:09] [textsecure] SyncMessage getSent             
DEBU[2021/01/24 14:17:09] [axolotl] handle sync message 161149422624
```

Even if there also is above:
```
ESC[37mDEBUESC[0m[2021/01/24 14:13:58] [axolotl-ws] error: read tcp 10.55.27.33:34520->76.223.92.165:443: read: connection timed out 
ESC[31mERROESC[0m[2021/01/24 14:13:58] [axolotl] error:  read tcp 10.55.27.33:34520->76.223.92.165:443: read: connection timed out 
ESC[37mDEBUESC[0m[2021/01/24 14:14:01] [textsecure] Websocket Connecting to signal-server 
ESC[31mERROESC[0m[2021/01/24 14:14:01] dial tcp: lookup textsecure-service.whispersystems.org on 127.0.1.1:53: server misbehaving 
ESC[37mDEBUESC[0m[2021/01/24 14:14:01] [axolotl-ws] error: dial tcp: lookup textsecure-service.whispersystems.org on 127.0.1.1:53: server misbehaving 
ESC[31mERROESC[0m[2021/01/24 14:14:01] [axolotl] error:  dial tcp: lookup textsecure-service.whispersystems.org on 127.0.1.1:53: server misbehaving
```

I think that the STR are, switch to UUID with some contacts, write a message with the desktop client to a contact to whom you didn't write with Axolotl 0.9.5, messages sent to the UUID contact using the desktop client are now displayed in the other contact conversations

**Comment by fabrei** [comment]
I can confirm this bug..I see the messages send with the desktop client in another chat. And until now I didn't write a message with axolotl version 0.9.5 in this chat the messages are displayed.

**Comment by Flaburgan** [comment]
This should be fixed by https://github.com/nanu-c/axolotl/pull/342 so in 0.9.6. I'm currently testing it and will confirm tomorrow.

**Comment by Flaburgan** [comment]
I didn't reproduce so I will consider this fixed.
