### ISSUE TITLE
axolotl crashes when starting [BUG]

### ISSUE THREAD

**Issue by soki3456** [nanu-c/axolotl#329]
### Description

since the latest update, axolotl crashes, I only see 1 second the starting screen, then the loading circle, and after that everything vanishes

### Steps to Reproduce

1. [First Step] https://paste.ubuntu.com/p/vT65S5tpZd/ - i downloaded the log-viewer and ho this is the right one for you to identify the problem; sorry for not beeing more competent on that, i'm learning. 
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Versions

Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`

#### Device
What device

#### Link to Debug Log
Please provide a link to debug

**Comment by Flaburgan** [comment]
Hello @soki3456 and thanks for taking time to report a problem. Can you please tell us which mobile phone you are using?

**Comment by soki3456** [comment]
Of course - its a NEXUS 5 hammerhead;

**Comment by nuehm-arno** [comment]
Is this issue still present in v1.0.5? If not, please close the issue.

**Comment by soki3456** [comment]
It is not relevant anymore. I changed to Android. Can you close it?

⁣BlueMail for Android herunterladen ​

**Comment by Flaburgan** [comment]
As the issue is very old, many things changed anyway. Closing it.
