### ISSUE TITLE
[BUG] inconsistent behaviour of contact list items

### ISSUE THREAD

**Issue by Danfro** [nanu-c/axolotl#334]
### Steps to Reproduce

1. In contact list, press&hold on an contact to select it.
2. Press&hold on another contact.
3. Press the "x" icon.

**Expected behavior:** [What you expect to happen]
a) I am not sure if the second step should allow to select multiple contacts, similar to main chat list. Currently only one contact is selectable.
b) The "x" icon should deselect the selected contact(s) and change the header to normal state.

**Bug/Actual behavior:** [What actually happens]
When pressing the "x" icon for the first time I do get a vertical line added next to the "x" and nothing else happens:

![screenshot20210127_061702031](https://user-images.githubusercontent.com/37637312/105946784-36f7b200-6068-11eb-9ffe-f538fac01425.png)

Pressing the "x" button a second time, the header is changed to normal state, BUT the selected contact stays selected. There is no way to deselect an contact.

#### Versions

0.9.5

#### Device
Ubuntu Touch, devel, Qt5.9

**Comment by nanu-c** [comment]
We removed the old contact handling now.
