### ISSUE TITLE
Application crash after contact’s safety number changed [resolved itself]

### ISSUE THREAD

**Issue by timothymctim** [nanu-c/axolotl#34]
### Description
A contact in my contact list got a new “safety number” and sent me a message.
The moment I replied, the application crashed. I restarted the application and everything seemed okay. However, when trying to open *any* chat, the application would crash again. In the mean time I could receive new messages, I got new push notifications, and I could also see the messages in the chat overview. Only selecting *any* chat made the application crash.

After some time (< 30 minutes), while I was trying to debug, the application didn’t crash anymore, and haven’t ever since. Meanwhile, I was using Signal Desktop to communicate to others.

When the application didn’t crash anymore, the message that I initially tried to send to my contact with the changed safety number, “magically” disappeared.

#### Versions
Signal for Ubuntu version `0.3.261`

#### Debug Log
Sadly, the debug log does not seem to contain any relevant log entries.

**Comment by nanu-c** [comment]
Interesting bug, I try to reproduce it. In Options you can turn on the debug log then maybe we have more informative notes.

**Comment by timothymctim** [comment]
Good to know for next time! Thanks.
However, if I go to Settings > Advanced and then select Activate Debuglog the box got checked. But, if I then click on “<” to go back and select Advanced again (to confirm that the option is selected), the Activate Debuglog option is again unselected. I haven’t verified if this is just a bug in the GUI or whether the option isn’t actually enabled.

**Comment by yo-k** [comment]
Can anybody confirm or deny that this behavior (Application crash after contact’s safety number changed) still exists?
