### ISSUE TITLE
Incoming Call and Outgoing Call Notification

### ISSUE THREAD

**Issue by AA303** [nanu-c/axolotl#361]
When there are an incoming/outgoing calls Axolotls create a separate chat with contact UUID and "callMessage" in the chat.

**Describe the solution you'd like**
Would it be possible to identify/link UUID to a Contact and put the message in the chat with that contact "Incoming Call" or "Outgoing Call", when called from the desktop client?

**Comment by Flaburgan** [comment]
Nanu published a new version of textsecure which should improve that. Actually I'm surprised  no changes are needed in Axolotl side but I'll build a clickable from the main branch tomorrow to test.
