### ISSUE TITLE
[BUG] Cannot register error

### ISSUE THREAD

**Issue by NlGHT** [nanu-c/axolotl#366]
### Description

I am trying to use axolotl and the first step is register of course.  But after submitting phone number in registration process it gives an error saying "Error communicating with Signal servers".  It does say on the register screen that there are issues with changes to signal upstream, but on the error screen is says to report the issue, so that's why i'm posting here.  Couldn't find any issues with it existing already, so apologies if this is redundant.

### Steps to Reproduce

1. Enter correct phone number and choose country (doesn't matter which country as i've tried two of my phone numbers from different countries)
2. Tap to submit the input
3. "Error communicating with Signal servers" dialog popup

**Expected behavior:** [What you expect to happen]
The phone number is registered successfully and I can continue to the name and rest of the registration process.

**Actual behavior:** [What actually happens]
![image](https://user-images.githubusercontent.com/36537208/107441804-2e0de280-6b36-11eb-9251-e635a5472a13.png)

#### Versions

It is a flatpak manual Qt build with local main branch at 006fa5c0a4127330eff5c5bc759d74ea6fefd933.

#### Device
I am using Pinephone with Manjaro Phosh.

#### Link to Debug Log
I couldn't find the requested log file ~/.cache/upstart/application-click-textsecure.nanuc_textsecure*.log but here is the console output: https://pastebin.com/SySywZfh

**Comment by AA303** [comment]
time="2021/02/09 20:58:32" level=error msg="[axolotl] error:  Need to solve captcha"

looks like captcha does not work.

I am on 0.9.7 on UT and it works.

**Comment by NlGHT** [comment]
> time="2021/02/09 20:58:32" level=error msg="[axolotl] error: Need to solve captcha"
> 
> looks like captcha does not work.
> 
> I am on 0.9.7 on UT and it works.

Interesting... I don't see any captcha's anywhere!  Where is it supposed to show up in the process?

**Comment by nanu-c** [comment]
In your logs it says, that you run `time="2021-02-09T20:58:01+01:00" level=info msg="[axolotl] Starting Signal for Ubuntu version 0.9.6"`. Captcha support was introduced in 0.9.7 so it will not show up in your version.

**Comment by Flaburgan** [comment]
Yes, please upgrade to the last version ;)
