### ISSUE TITLE
[BUG] Axolotl does not start on PinePhone

### ISSUE THREAD

**Issue by skchande** [nanu-c/axolotl#376]
### Description

If I click on the Axolotl icon, the application overview closes and I can see my desktop background. Axolotl did not start started.

### Steps to Reproduce

1. Install Mobian on PinePhone 

2. Install Axolotl via snap
`sudo snap install --channel=edge axolotl`

**Expected behavior:**
Axolotl should start.

**Actual behavior:** 
Axolotl did not start

#### Versions
Axolotl 0.9.8

#### Device
Mobian bullseye/sid

#### Link to Debug Log
The folder 'upstart' does not exist under '~/cache/'
So I could not find the log, if it even exists.

**Comment by nanu-c** [comment]
Currently the snap package is not intended for mobian, please refer to https://wiki.mobian-project.org/doku.php?id=axolotl&s[]=axolotl for working mobian solution.
If you really want to use the snappackage you need to start it from terminal with `axolotl -e qt`

**Comment by nuehm-arno** [comment]
Hi,

axolotl -e qt is currently not working on Mobian / Pinephone as described here

https://github.com/nanu-c/axolotl/issues/335

Or is there a workaround?

**Comment by skchande** [comment]
I can confirm the error:

```
mobian@mobian:~$ axolotl -e qt
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
INFO[0000] [axolotl] Starting Signal for Ubuntu version 0.9.8 
INFO[0000] [axolotl] Setup completed                    
INFO[0000] [axolotl] Axolotl-gui starting for sys: qt   
DEBU[0000] [axolotl] Run Backend                        
FATA[0000] cmd.Start() failed with 'exec: "qmlscene": executable file not found in $PATH' 

```

**Comment by olof-nord** [comment]
It seems that there is something with the qmlscene package which could be relevant. What is the exact version used?
Also, what is your $PATH? Perhaps qmlscene is installed, but somehow missing.

**Comment by Id2ndR** [comment]
I successfully start Axolotl 1.0.0 on PinePhone running snap version on Manjaro. I think this issue can be closed now.
