### ISSUE TITLE
[BUG] Unable to add a contact

### ISSUE THREAD

**Issue by ChrisAWC** [nanu-c/axolotl#381]
### Description
After (re)installing Axolotl, am not able to (re)add a contact

### Steps to Reproduce

1.Menu> Contacts> "+" > add name & phone number 
2. Enter Name and Phone number> tap outside data entry area to close keyboard and to be able to see "Add"
3. tap "Add" This results in a return to the initial page "Contact list is empty..."

This is a new problem. It was initially possible to add contacts. Then after the problem described in Bug Report #330, UT Tweak Tool was used to remove data, Axolotl uninstalled then re-installed. Since re-installing Axolotl, unable to add a contact.

[application-click-textsecure.nanuc_textsecure_0.9.8.log](https://github.com/nanu-c/axolotl/files/5994987/application-click-textsecure.nanuc_textsecure_0.9.8.log)

**Expected behavior:**To see the Contact that has just been entered

**Actual behavior:** as above: ""Contact list is empty...""

#### Versions

Axolotl 0.9.8
UT: Ubuntu 16.04 (OTA-15)

#### Device
Nexus 5/UT

#### Link to Debug Log
Please provide a link to debug from ~/.cache/upstart/application-click-textsecure.nanuc_textsecure*.log
Be careful it contains sensible data

**Comment by seteahconnoc** [comment]
Anything new regarding this issue? I'm experiencing a similar behavior. Feel free to ask for further details.

**Comment by ChrisAWC** [comment]
Hi seteahconnoc, Nothing new. I have tried adding contacts (individuality, as above), but unsuccessfully. Not sure why this is happening. My next step was to add contacts in a different way: Menu>Contacts>(Menu) Import contacts, from a .vcf file. But I haven't tried it yet. If successful, I will report back.
Regards ChrisAWC

**Comment by seteahconnoc** [comment]
Thanks for the quick response. - In order to get a result, I uninstalled and reinstalled axolotl. Obviously, this didn't delete my old contacts. What would be the proper way to purge? How do I delete the old axolotl contacts? Any help on this would be welcome.

**Comment by ChrisAWC** [comment]
Hi, I asked the same question, and received the following from "Fla":

_Sorry I didn't take time to have a look at your bug report. I will try to do it this week. If you really want to wipe Axolotl data, you can do so using the app UTTT that you can find in the OpenStore. You are using Ubuntu Touch right?_

UTTT seems to be "UT Tweek Tool": available in the OpenStore. When I used it I chose to delete all three categories of data offered. It was after that that I couldn't add a contact. I would try deleting one at a time if I was to do it again!
BTW the contact I have been trying to add has a Netherlands phone number. Not sure if that is relevant, but I did see that someone had difficulty adding contacts from a particular country.
All the best!

**Comment by seteahconnoc** [comment]
@ChrisAWC Thanks for your detailled answer. I'm curious how this will work out for me.

**Comment by Flaburgan** [comment]
Hello everyone and sorry to be late to answer you. We found that this bug only applies to armhf devices (Fairphone 2, Nexus 5 for example) and not to arm64 ones (like the Volla phone). The problem is an integer overflow for 32bits phones. I would love @Blackoverflow and @nanu-c to focus on it and find a way to solve it because it is a critical problem in my opinion.

**Comment by seteahconnoc** [comment]
@Flaburgan Thank you for your efforts on solving this problem.

BTW There are the specifications of my device: OnePlus One (bacon) 16.04.7 LTS armhf (armv7l) OTA-15

**Comment by Flaburgan** [comment]
More technical details: on armhf, contact import is failing with: `Could not get create createDiscoveryRequest strconv.ParseInt: parsing "+33612121212": value out of range` so it is an arm32 overflow error while converting a string to an int. int64 is used in 4 places in the code and that doesn't work for arm32.

Here is the full log:
```
[37mDEBU[0m[2021/03/07 22:52:13] GET /v1/directory/auth 200                   
[37mDEBU[0m[2021/03/07 22:52:13] [textsecure] getCredentials                  
[37mDEBU[0m[2021/03/07 22:52:13] [textsecure] GetAndVerifyMultiRemoteAttestation 
[37mDEBU[0m[2021/03/07 22:52:14] [textsecure] PUT /v1/attestation/cREPLACEDHASH5 200 
[37mDEBU[0m[2021/03/07 22:52:14] [textsecure] GetAndVerifyMultiRemoteAttestation key  
[37mDEBU[0m[2021/03/07 22:52:14] [textsecure] validateAndBuildRemoteAttestation  <nil> 
[37mDEBU[0m[2021/03/07 22:52:14] [textsecure] GetRegisteredContacts assestations 
[37mDEBU[0m[2021/03/07 22:52:14] [axolotl] Refresh contacts count:  0         
[31mERRO[0m[2021/03/07 22:52:14] Could not get create createDiscoveryRequest strconv.ParseInt: parsing "+33612121212": value out of range 
[37mDEBU[0m[2021/03/07 22:52:14] [axoltl] update session names + uuids   
```

**Comment by ejpcmac** [comment]
@Flaburgan Try to replace this line:

https://github.com/signal-golang/textsecure/blob/master/contactDiscoveryCrypto/contactDiscoveryCrypto.go#L104

with:

```go
strconv.ParseInt(s, 10, 64)
```

It will force `strconv.ParseInt` to return an `int64` regardless the architecture. Currently, it returns an `int`, which is bound to the architecture’s word size.

**Comment by huggymann** [comment]
Hello, can anyone actually make a build for that to test it?

**Comment by huggymann** [comment]
okay, i did a build today and i can see that contacts are working . WOHOOOO! i cannot believe :)

**Comment by huggymann** [comment]
would one of you like to try out the package as well on different device than mine (oneplus one utouch ota 17) ?

**Comment by trollordragon** [comment]
Hey all!
I'm experiencing this issue on my Pine64 Pinephone, using Manjaro Arm.
I installed axolotl 1.0.0-1 which was packaged in a aarch64 AUR package, which is based on the ubuntu arm64 .deb package. See [here](https://aur.archlinux.org/packages/axolotl-bin/)
I'm using this package as the snapd package, which is available for manjaro arm, does not work (I can launch axolotl, but I can't enter text).

It worked after the installation and I added 4 contacts manually. There is no error message in stdout when I try to add a contact, at least I do not recognize one. See attached output. In Line 37 it says "Add contact "****". But the contact does not appear in the contact list. Please note that I deleted some parts of the stdout output as I did send some messages between launching the application and trying to add a contact.

[axolotl_stdout.txt](https://github.com/nanu-c/axolotl/files/6760563/axolotl_stdout.txt)

**Comment by nuehm-arno** [comment]
Is this issue still present in v1.0.5? If not, please close the issue.

**Comment by trollordragon** [comment]
As it hapoens, I installed 1.0.5 this evening. I can't add contacts, as pressing "add" does not have any effect. So it's different to the above described bug. I thought about adding the contacts manually, but there is no contacts file in .config/textsecure... and, beside that, I don't know the format, a contact should be saved in such a file (in case I create it myself).

**Comment by ChrisAWC** [comment]
Updated to v1.0.5. Attempted to add contact: Added name and phone number, touched "Add" button. Button changed to show pale edge, then no further activity. This is slightly different from previously (when contact entry page would close), but still not able to add a contact.
Nexus 5.

**Comment by nuehm-arno** [comment]
I can confirm, that with v1.0.5 (Mobian@Pinephone) adding contacts is not possible.

**Comment by 4c2** [comment]
https://github.com/nanu-c/axolotl/issues/576 describes the contact import issue in v1.0.5 also in detail.

**Comment by trollordragon** [comment]
With 1.0.7. the "add" button can be pressed, but I was only able to add a single contact. Adding more contacts failed, as pressing "add" closes the add contact window, but the contact does not appear. It's a fresh axolotl installation on Manjaro arm. There were no existing contacts.

**Comment by ChrisAWC** [comment]
Still not able to add save a contact in 1.0.7 (on Nexus 5)

**Comment by nuehm-arno** [comment]
On Mobian@PinePhone (v1.0.7) it is possible to add new contacts via Menu --> Contacts --> + and they are persistent.

**Comment by trollordragon** [comment]
Attached stdout from Axolotl while I tried to add a contact. Most of the file contains error messages from a different bug (#569). At line 362 it shows my attempts to add two different contacts manually (I "x" the names out).
[axolotl_stdout.txt](https://github.com/nanu-c/axolotl/files/7486798/axolotl_stdout.txt)

**Comment by trollordragon** [comment]
is this a duplicate of #314? 

Someone mentioned the possibility to add a contact by editing a file in a textsecure subfolder in  the home directory. I can't find this thread anymore. Might be a useful workaround.

**Comment by nanu-c** [comment]
Closed in https://github.com/nanu-c/axolotl/pull/757
