### ISSUE TITLE
Removed from group chat because Signal not updated

### ISSUE THREAD

**Issue by polypode** [nanu-c/axolotl#390]
### Description

I was removed from a group chat today. Other group members receive a message that I was removed from the group because I did not update signal. My group thread shows me as removed from the group and I can not make new posts.

### Steps to Reproduce

1. As other group member, open group thread
2. Enter message and send

**Expected behavior:** [What you expect to happen]
The message should be sent to all group members

**Actual behavior:** [What actually happens]
A notification says that group member X has been removed from group because Singal was not updated

**Reproduces how often:** [What percentage of the time does it reproduce?]
3/3 instances

#### Versions
Axolotol Beta 0.9.8 

#### Device
Fairphone2 with UbuntuTouch OTA15

#### Link to Debug Log
Please provide the link generated by `Settings->Advanced-> Submit Debug Log`

#### Else
Last successful group post on Feb 18th, notice of deletion Feb 21st

**Comment by nanu-c** [comment]
Thank you for taking the time and opening an issue. I close this in favor of #296. Please see that issue for groupsv2 support. Ask your friend to create a new group and ask them to not update the group until we have groupv2 support.
