### ISSUE TITLE
[BUG] contact sync with Signal desktop broken with 0.9.9 prerelease

### ISSUE THREAD

**Issue by Danfro** [nanu-c/axolotl#391]
### Description

With the prerelease of 0.9.9 I can not sync my contacts with Signal Desktop v1.40.0 anymore.
@nanu-c did NOT confirm this, he still seems to be able to sync.

This might be due to contacts with no uuid or an edgecase uuid starting and ending with zeros I am having.

This is from Signal Desktop log suggesting the above:
```
WARN  2021-02-21T14:50:54.795Z Normalizing invalid uuid: 00000000-0000-0000-0000-000000000000 at path uuid in context "ProtoParser::next (proto.uuid)"
INFO  2021-02-21T14:50:54.798Z handleContacts: finished
ERROR 2021-02-21T14:50:54.800Z Invalid contact received: Invalid UUID
```

**Comment by nuehm-arno** [comment]
Is this issue still present in v1.0.5? If not, please close the issue.
