### ISSUE TITLE
Link axolotl as device to an existing client

### ISSUE THREAD

**Issue by pothos** [nanu-c/axolotl#400]
If an existing Signal client is used on another device it's possible to connect Signal Desktop to that client. It would be nice to have axolotl also join an existing account this way instead of forcing a recreated new account it owns. E.g., you can use signal-cli to manage the account and connect devices to it with `signal-cli -u +123456789 addDevice --uri "tsdevice:/?uuid=f...."` or you can use the official mobile clients of Signal to link secondary devices.

**Describe the solution you'd like**
On first start ask to either use the SMS method to create a new account or join an existing one by linking axolotl as new device.

**Comment by nanu-c** [comment]
That's not possible at the moment because we don't replace signal desktop but signal android/iOS.
For now we copy more or less the android code into golang and  for this feature request we need to start to copy the logic from signal desktop.

**Comment by ehsjoar** [comment]
You can move your Signal account from one Android device to another. Is it possible to move from an Android device running Signal to a Linux phone running Axolotl? If not, the use case is basically limited to new Signal users, right?

**Comment by nanu-c** [comment]
#985 will solve this problem
