### ISSUE TITLE
[BUG] Unable to Start New Conversation

### ISSUE THREAD

**Issue by AA303** [nanu-c/axolotl#402]
### Description

Existing contacts are greyed out. Taping on the contact does not start a new conversation.

### Steps to Reproduce

1. Open Axolotl
2. Go to Contacts
3. Find all existing contacts greyed out
4. Tap on any contact

**Expected behavior:** [What you expect to happen]

New chat with selected contact to open

**Actual behavior:** [What actually happens]

Tapping on greyed out contact does not trigger any action. 

#### Versions

0.9.9

#### Device
Volla Phone + UT

#### Link to Debug Log

 [axolotl] Refresh contacts count: 0

**Comment by Tob-end** [comment]
I have the same issue un my FP2 with UT.
I tried to delete contacts or create new ones, that doesn't work either. I even deleted my account to clear the contactlist, but now its empty and I can't import or create new contacts.

**Comment by nanu-c** [comment]
The bug is confirmed on armhf because we have a buffer overrun for a 64bit value. @Blackoverflow  is researching into the issue. If it also persists on volla, we have to research the bug further. Nevertheless we are adding better errorhandling to see what's going on here.

**Comment by nanu-c** [comment]
This is solved, if not please reopen.
