### ISSUE TITLE
[axolotl-web] Upgrade to Node.js v14

### ISSUE THREAD

**Issue by olof-nord** [nanu-c/axolotl#412]
**Is your feature request related to a problem? Please describe.**

We currently use node.js v12 for axolotl-web.

v12, "Erbium", is currently in Maintenance LTS status, which is scheduled to end 2022-04-30.

**Describe the solution you'd like**

I suggest to upgrade to the current Active LTS, "Fermium", which is version 14.

Looking into the vue documentation, I couldn't find much info, but their [CI examples](https://cli.vuejs.org/guide/deployment.html#gitlab-pages) uses the node docker "latest" tag, which currently is v15.

If v15 is supported, I assume that also v14 should be no problem.

https://nodejs.org/en/blog/release/v14.0.0/

https://nodejs.org/en/about/releases/

**Comment by Flaburgan** [comment]
Vue is run by electron, so it's not related to NodeJS if I understand all that right. NodeJS is needed to build the initial dependencies.

**Comment by olof-nord** [comment]
Ah, I see. Then an upgrade should go smooth, and have the possibility to cause less issues.

**Comment by nanu-c** [comment]
I am actually using node v15.2.1 and npm version 7.0.12 for development. So we can update it without problems
