### ISSUE TITLE
[axolotl] Upgrade to go 1.16

### ISSUE THREAD

**Issue by olof-nord** [nanu-c/axolotl#417]
**Is your feature request related to a problem? Please describe.**

axolotl currently lists go `1.15` in the go.mod.

We do however, use to 1.16 for the Flatpaks, as that is the current version provided by our helper util (org.freedesktop.Sdk.Extension.golang).

**Describe the solution you'd like**

I suggest we upgrade to go `1.16`.

**Additional context**

From the release notes:

> As always, the release maintains the Go 1 promise of compatibility. We expect almost all Go programs to continue to compile and run as before. 

 Go 1.16 Release Notes 
https://golang.org/doc/go1.16

**Comment by Flaburgan** [comment]
Does this really bring something? Which version of go is there in the ubuntu repository at the moment? I don't want to increase the entry barrier for newcomers

**Comment by olof-nord** [comment]
Very valid question.

Ubuntu Focal Fossa (20.04 LTS) installs `1.13` if no version is provided.
https://packages.ubuntu.com/focal/golang

Ubuntu Groovy Gorilla (20.10) installs `1.14` if no version is provided.
https://packages.ubuntu.com/groovy/golang

Ubuntu Hirsute Hippo (21.04), set to be released 2021-04-22, installs `1.16` if no version is installed.
https://packages.ubuntu.com/hirsute/golang

I think we should re-word and simplify the getting started [section](https://github.com/nanu-c/axolotl#installation-of-development-environment) in the main readme in order to lower the barrier for newcomers.

We currently have no information in the readme regarding installing neither golang nor node/npm. We could detail exactly step by step how to do so - or better even link to official golang and/or node.js sources or similar official documentation.
