### ISSUE TITLE
[BUG] "Request code" button not working on Mobian

### ISSUE THREAD

**Issue by nuehm-arno** [nanu-c/axolotl#469]
### Description
Hello there,
pressing the "Request code" button is resulting in no action in Axolotl - neither in the app nor using a browser on Mobian.

### Steps to Reproduce
1. Start a fresh installation of Axolotl.
2. Press next in the welcome screen.
3. Type in a phone number and press the "Request code" button.
4. Nothing happens.

**Expected behavior:**
The request is sent to the Signal servers.

**Actual behavior:**
Nothing happens.

#### Versions
v0.9.9 (built 12.04.2021 on Mobian)

#### Device
Pinephone / Mobian

#### Link to Debug Log
systemd log attached (grep with "axolotl" and "textsecure")
[axolotl_request_bug.txt](https://github.com/nanu-c/axolotl/files/6313512/axolotl_request_bug.txt)

**Comment by maesi89** [comment]
Hey
Same here with the newest qt flatpak on my Pinephone with Manjaro Plasma.

**Comment by nuehm-arno** [comment]
Using
`export GO111MODULE=on && go get -d github.com/nanu-c/axolotl@v0.9.9`
to get the source is producing a binary with a working "Request code" button... so it must be some changes in main, which cause the trouble.

**Comment by nanu-c** [comment]
I have solved it in https://github.com/nanu-c/axolotl/pull/472 it's specific for chromium usage

**Comment by nuehm-arno** [comment]
Works fine in v1.0.0.
