### ISSUE TITLE
[BUG] Group Messages are appearing as messages from individual group members for existing groups

### ISSUE THREAD

**Issue by torfmaster** [nanu-c/axolotl#470]
### Description

Group Messages are appearing as messages from individual group members. In the UI I cannot distinguish between messages sent inside the group and messages sent directly.

### Steps to Reproduce

1. Use axolotl with an existing Signal account (previously run on some Android device) contained in a group
2. Let someone send a message to the group

**Expected behavior:** [What you expect to happen]
Message is displayed as a "group message"

**Actual behavior:** [What actually happens]
Message is displayed as an individual message.

#### Versions

0.9.8

#### Device
Pinephone64 with Mobian

**Comment by nanu-c** [comment]
That's going to be resolved, when https://github.com/nanu-c/axolotl/issues/296 is closed :)

**Comment by nanu-c** [comment]
Thank you for taking your time to report the issue !

**Comment by torfmaster** [comment]
Thanks for the prompt response. I'd be okay with treating this issue as a duplicate or (as this problem might occur to others as well) keep it open for future reference.

**Comment by nuehm-arno** [comment]
Should be resolved with v1.0.0.
