### ISSUE TITLE
Enhancement: Dark mode for signal app

### ISSUE THREAD

**Issue by Rom4nB** [nanu-c/axolotl#50]
### Description
As there is still no "redshift/blue light filter" in UT implemented, it would be nice when the Signal app would offer a "dark mode" for writing in the evening, similar like the SMS, Telegram or Matrix app.

**Comment by yo-k** [comment]
I have testet UT Tweak Tool -> systemdesign -> SuruDark
this signal app does not care about it and shines bright as always :-)

@nanu-c enhancement tag?

**Comment by Flaburgan** [comment]
Do you know if:
- QTWebEngine (or the engine embed in Axolotl, I'm not familiar with that yet) is supporting [@media (prefers-color-scheme: dark)](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)?
- UT is proving the good information about the used theme?

If so then I could be able to deal with that.

**Comment by Flaburgan** [comment]
I just created a dark page test and unfortunately Morph and Demo browser are displaying it light even if I have the suru dark theme. @nanu-c can you tell us what's the engine used by Axolotl? Here is the test page if you want to try:
```html
<!DOCTYPE html>
<html>
  <head>
		<title>Test dark mode</title>
		<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
      @media (prefers-color-scheme: dark) {
        body { background-color: #336; }
        h1 { color: #ccc; }
      }
    </style>
  </head>
  <body>
    <h1>Test suru-dark</h1>
  </body>
</html>
```

**Comment by Flaburgan** [comment]
Good news, @nanu-c and myself just added that feature, with the new release, you can now switch to the dark mode in the settings panel. Enjoy!

**Comment by nanu-c** [comment]
And it's in the open-store yeai
