### ISSUE TITLE
[BUG] Failing to build on fedora 35 AARCH64

### ISSUE THREAD

**Issue by xnuken** [nanu-c/axolotl#502]
### Description
When building on FEDORA 35 AARCH64 I get `get "launchpad.net/gocheck": found meta tag vcs.metaImport{Prefix:"launchpad.net/gocheck", VCS:"bzr", RepoRoot:"https://launchpad.net/~niemeyer/gocheck/trunk"} at //launchpad.net/gocheck?go-get=1
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: unrecognized import path "launchpad.net/gocheck": GOVCS disallows using bzr for public launchpad.net/gocheck; see 'go help vcs'
make: *** [Makefile:40: build-axolotl] Error 1
`
[Description of the issue]
See above
### Steps to Reproduce

1. [First Step] Build on fedora 35
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
To build fine
**Actual behavior:** [What actually happens]
`get "launchpad.net/gocheck": found meta tag vcs.metaImport{Prefix:"launchpad.net/gocheck", VCS:"bzr", RepoRoot:"https://launchpad.net/~niemeyer/gocheck/trunk"} at //launchpad.net/gocheck?go-get=1
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: unrecognized import path "launchpad.net/gocheck": GOVCS disallows using bzr for public launchpad.net/gocheck; see 'go help vcs'
make: *** [Makefile:40: build-axolotl] Error 1
`
#### Versions

Please provide the Version as written in `Settings->About Axolotl`

#### Device
What device or OS are you using? Fedora 35 AARCH64 PinePhone

#### Link to Debug Log
Please provide a link to debug from ~/.cache/upstart/application-click-textsecure.nanuc_textsecure*.log
Be careful it contains sensible data

**Comment by nanu-c** [comment]
Can you try it again?
