### ISSUE TITLE
[BUG] [Copied Issue] Outgoing messages do not work, incoming are OK

### ISSUE THREAD

**Issue by nuehm-arno** [nanu-c/axolotl#504]
### Description
Outgoing messages only get one "tick" and are not received by others.
(Copy from here https://github.com/nuehm-arno/axolotl-mobian-package/issues/4)

**Expected behavior:**
Messages are received by others.

**Actual behavior:**
I had this problem with previous version and now with v1.0 and have not been able to cure it. In short my Axolotl seems unable to get anything back to the Signal servers (outgoing messages, even confirmations that I have read messages) but can receive incoming messages fine.
I attach a log from Mobian of a fresh install. I have redacted some digits in my phone number and some characters in contact names. The log includes the initial setup (including Captcha), then I add 3 contacts, then at around 16:17:16 I receive a message in a group. Then I try to send a response that (an hour later) I still only have 1 tick for in my Axolotl.

#### Versions
v1.0.0

#### Device
Pinephone/Mobian

#### Link to Debug Log
https://github.com/nuehm-arno/axolotl-mobian-package/files/6562002/axolotl.log

**Comment by selfbc** [comment]
Does this still not work for you?  Signal changed something server side in the US and UK and it is now working for me.  Seemed to only affect certain countries.  I close my similar issue (https://github.com/nanu-c/axolotl/issues/474).

**Comment by nuehm-arno** [comment]
Yes, I asked the OP and it is working. Thanks for reminding!
