### ISSUE TITLE
[BUG] Error after Update

### ISSUE THREAD

**Issue by 0unknwn** [nanu-c/axolotl#511]
After updating the flatpak version of Axolotl, I couldn't start it anymore receiving this error message:

`axolotl: error while loading shared libraries: libzkgroup_linux_amd64.so: cannot open shared object file: No such file or directory`

I am running Ubuntu 21.04.

**Comment by Torbuntu** [comment]
https://github.com/flathub/org.nanuc.Axolotl/issues/3

Same here.

**Comment by 0unknwn** [comment]
It is working again. Thanks for fixing it!
