### ISSUE TITLE
[BUG] axolotl 1.0.0 fails to start (mobian pinephone)

### ISSUE THREAD

**Issue by sc0w** [nanu-c/axolotl#515]
axolotl 1.0.0 fails to start (mobian pinephone)

I followed the mobian axolotl `manual installation` on the wiki:
https://wiki.mobian-project.org/doku.php?id=axolotl

I see in terminal:

`./axolotl : error while loading shared libraries: libzkgroup_linux_arm64.so: cannot open shared object file: No such file or directory`

I see this file on folder: `~/go/src/github.com/nanu-c/zkgroup/lib`

what addition step I need?

Thanks!

**Comment by sc0w** [comment]
I solve this issue copying the file to `/usr/lib` and later `ldconfig -n -v /usr/lib`

https://www.golinuxhub.com/2014/03/how-to-install-libraries-manually-in/

**Comment by duncan-bayne** [comment]
Hi :)  I'm experiencing [this issue right now](https://gitlab.com/duncan-bayne/pinephone-setup/-/issues/3) on Mobian - any chance we could please re-open until the Snap uses the libraries from the default location?  Looks like it's still a problem.
