### ISSUE TITLE
Installing the app on ubports

### ISSUE THREAD

**Issue by pparent76** [nanu-c/axolotl#520]
Hi,

Probably a stupid question, but I cannot seem to be able to install the newest version of axolotl on ubports 16.04.6.

It is not listed on my openstore anymore, and if I download the package by hand I cannot install it.

https://open-store.io/app/textsecure.nanuc

It might be related to the fact that ubuntu-sdk-16.04.4  is required by the app?

Thank's a lot!

Pierre.

**Comment by Flaburgan** [comment]
hello @pparent76 and thank you for taking time to fill an issue. Can you please tell us which version of Ubuntu Touch you are using (is it OTA-17?) and what is the model of your phone (is it armhf or arm64?)

**Comment by pparent76** [comment]
I use  16.04.6 on Nexus 5.

**Comment by realflow100** [comment]
> Hi,
> 
> Probably a stupid question, but I cannot seem to be able to install the newest version of axolotl on ubports 16.04.6.
> 
> It is not listed on my openstore anymore, and if I download the package by hand I cannot install it.
> 
> https://open-store.io/app/textsecure.nanuc
> 
> It might be related to the fact that ubuntu-sdk-16.04.4 is required by the app?
> 
> Thank's a lot!
> 
> Pierre.

Sorry for replying here but I havent found any other way to message you! I'm wondering if theres any way to obtain the magic lantern module you've made Specifically the AV video record module. Theres no release available. and I dont know how to even begin attempting trying to compile something myself. its not available on the magic lantern forum anymore. broken old links.

**Comment by pparent76** [comment]
@realflow100 

Why did you not open an issue on the given repository?

**Comment by pparent76** [comment]
@Flaburgan do you need further information on my version of ubports?

**Comment by nanu-c** [comment]
@pparent76  is this still an issue?

**Comment by pparent76** [comment]
Yes it is still an issue

**Comment by nanu-c** [comment]
ota16 is 16.04.4 and I think you have to update it

**Comment by dobey** [comment]
You must not be on OTA 16, as it includes the upgrade to Qt 5.12 and `ubuntu-sdk-16.04.5` framework version, which is required for apps built against Qt 5.12 or (most) QML module imports from it.

Please state which device you are running Ubuntu Touch on, and the exact string of the _OS_ line in the _About_ page in _System Settings_, which states what image you are running.

Thanks.

**Comment by pparent76** [comment]
>ota16 is 16.04.4 and I think you have to update it

I'm currently at 16.04.6 this must be a more recent version.

**Comment by pparent76** [comment]
>Please state which device you are running Ubuntu Touch on, and the exact string of the OS line in the About page in System Settings, >which states what image you are running.

Ubuntu 16.04 LTS - armhf (20190427)

Last update: 26/02/2021

**Comment by pparent76** [comment]
Well anyway I just crashed the device trying to do apt-get upgrade. I will have to reflash it.

**Comment by pparent76** [comment]
After the reflash I can install it again! Thank's a lot!
