### ISSUE TITLE
[BUG] aarch64 flatpak build

### ISSUE THREAD

**Issue by langfingaz** [nanu-c/axolotl#521]
### Description

Local flatpak build (qt-version) fails on **aarch64** with the following error on startup:

```
axolotl: error while loading shared libraries: libzkgroup_linux_arm64.so: cannot open shared object file: No such file or directory
```

On my **amd64** machine a local flatpak build with the exact same steps (except the start command) works as expected.

### Steps to Reproduce

```shell
flatpak install flathub org.kde.Platform//5.15 && \
  flatpak install flathub org.kde.Sdk//5.15 && \
  flatpak install flathub org.freedesktop.Sdk.Extension.golang//20.08 && \
  flatpak install flathub org.freedesktop.Sdk.Extension.node14//20.08 && \
  flatpak install flathub io.qt.qtwebengine.BaseApp//5.15
```
```shell
mkdir -p ~/Downloads/git && cd ~/Downloads/git && git clone https://github.com/nanu-c/axolotl && cd axolotl
```
```shell
flatpak-builder --user --install --force-clean  build flatpak/qt/org.nanuc.Axolotl.yml
```

Start with:

```shell
/usr/bin/flatpak run --branch=main --arch=aarch64 --command=axolotl org.nanuc.Axolotl -axolotlWebDir=/app/bin/axolotl-web/dist -e=qt
```

**Expected behavior:**

According to [flatpak/qt/org.nanuc.Axolotl.yml](flatpak/qt/org.nanuc.Axolotl.yml) `libzkgroup_linux_arm64.so` should reside somewhere inside `~/.local/share/flatpak/app/org.nanuc.Axolotl/aarch64/main/.../files/lib/`. 

**Actual behavior:**

But this is not the case. `libzkgroup_linux_arm64.so` **is missing**!

```shell
[alarm@danctnix ~]$ sudo find / -name "libzkgroup*"
find: ‘/run/user/1000/doc’: Permission denied
```

**On my amd64 machine:**

Here the missing `libzkgroup*` exists (as expected) in multiple locations:

```shell
[yoda@fedora axolotl]$ sudo find / -name "libzkgroup*"
/home/yoda/.local/share/flatpak/app/org.nanuc.Axolotl/x86_64/main/624a5ad4ff23c3dec0355d67b8bbb36a8414a60fed6e5f103bfd2e519f311629/files/lib/libzkgroup_linux_amd64.so
/home/yoda/Downloads/git/axolotl/build/files/lib/debug/lib/libzkgroup_linux_amd64.so.debug
/home/yoda/Downloads/git/axolotl/build/files/lib/libzkgroup_linux_amd64.so
find: ‘/run/user/1000/doc’: Permission denied
find: ‘/run/user/1000/gvfs’: Permission denied
/var/lib/flatpak/app/org.signal.Signal/x86_64/stable/473e8075e5191d06f5ce0dbcd06bcf5848c3c59c06e08dc0f472706007777147/files/Signal/resources/app.asar.unpacked/node_modules/zkgroup/libzkgroup.dylib
/var/lib/flatpak/app/org.signal.Signal/x86_64/stable/473e8075e5191d06f5ce0dbcd06bcf5848c3c59c06e08dc0f472706007777147/files/Signal/resources/app.asar.unpacked/node_modules/zkgroup/libzkgroup.so
```

The last two lines are from a Signal Desktop installation through flatpak but all other occurrences come from building axolotl. All of these are missing when doing the same on the PinePhone with aarch64.

#### Versions

Latest git commit: [dfa44b1b3baed7a17fcdeb0d760d612f7cd3a361](https://github.com/nanu-c/axolotl/commit/dfa44b1b3baed7a17fcdeb0d760d612f7cd3a361)

#### Device

I have tried this on my PinePhone with Pine64Arch and with Manjaro.

**Comment by olof-nord** [comment]
I dont run KDE, and thus it seems that the KDE build is falling a bit behind.

However for the Flathub release, both a `x86_64` and an `aarch64` build is built by their build system, and that seems to work.

If you install the electron based version which is published on Flathub, do you run into the same error?

**Comment by nanu-c** [comment]
#985 will solve this.
