### ISSUE TITLE
[BUG] [Copied Issue] Contacts can not be deleted/edited

### ISSUE THREAD

**Issue by nuehm-arno** [nanu-c/axolotl#530]
### Description

After adding a contact its not possible to correct/change/delete the entry.

#### Versions
v1.0.0

#### Device
Mobian@PinePhone

**Comment by utuser** [comment]
This would - indeed - be a great feature.
Version: 1.0.4
Device UT@Vollaphone

**Comment by nuehm-arno** [comment]
Should be resolved with v1.0.5... Please confirm and close the issue.

**Comment by nanu-c** [comment]
Closed in https://github.com/nanu-c/axolotl/pull/757
