### ISSUE TITLE
Web links are opened in Axolotl instead of browser

### ISSUE THREAD

**Issue by kallekruse** [nanu-c/axolotl#538]
To reproduce send a link to yourself in Axolotl, e.g. to https://ubports.com .
Click on this link after the message has arrived.
Current behavior: Web page is opened in Axolotl. I am not able to return to the Axolotl UI, unless I close and restart Axolotl.
Expected behavior: Web page is opened in browser, Morph in my case. Axolotl UI stays usable.

Version: Axolotl Beta 1.0.0 from Ubports OpenStore.
On Sony Xperia X running latest Ubports.

This behavior appeared at some point in time (some months ago?) - before that web links worked as expected in Axolotl.

**Comment by ateliernz** [comment]
I have the same issue on Ubuntu Touch on FP2
