### ISSUE TITLE
[BUG] device may be undefined in DeviceList.vue, leading to a blank screen

### ISSUE THREAD

**Issue by raphj** [nanu-c/axolotl#540]
### Description

For whatever reason (maybe I did not complete a pairing, or something like this), I ended up having one `device` be undefined in the `devices` list used in `DeviceList.vue`. This leads to a Javascript error being thrown, rendering the device list screen empty and unusable.

I was able to pair a device by applying this patch:

```
diff --git a/axolotl-web/src/pages/DeviceList.vue b/axolotl-web/src/pages/DeviceList.vue
index a172e48..bc02fd8 100644
--- a/axolotl-web/src/pages/DeviceList.vue
+++ b/axolotl-web/src/pages/DeviceList.vue
@@ -3,7 +3,7 @@
     <!-- The first device is the main device and should not be shown -->
     <div v-if="devices && devices.length > 1">
       <div v-for="device in devices" :key="device.id" class="row device">
-        <div v-if="device.id != 0" class="col-10">
+        <div v-if="device && device.id != 0" class="col-10">
           <div class="device-name">{{ device.name }}</div>
           <div class="meta">
             <span class="lastSeen">
@@ -12,7 +12,7 @@
             </span>
           </div>
         </div>
-        <div class="col-2 actions">
+        <div v-if="device" class="col-2 actions">
           <button class="btn" @click="delDevice(device.id)">
             <font-awesome-icon icon="trash" />
           </button>
```

### Steps to Reproduce

Unfortunately, I don't know how I ended up with an undefined device. It could be that I tried to pair signal-cli, and then attempted to pair the same instance again, invalidating the first pairing. signal-cli isn't happy with this, but only after generating a pairing link so it could be that the first pairing was invalidated at that moment.

**Expected behavior:** [What you expect to happen]

The device list should never be blank.

**Actual behavior:** [What actually happens]

The device list can be rendered blank.

#### Versions

textsecure.nanuc 1.0.1.1 linux arm64 go1.15.9 (from the mobian package)

#### Device

Pinephone, Mobian

#### Link to Debug Log

(From the Firefox dev tools)

```
 TypeError: e.device is undefined
    r DeviceList.vue:8
    Ue runtime-core.esm-bundler.js:846
    update runtime-core.esm-bundler.js:4359
    n reactivity.esm-bundler.js:42
    Qt runtime-core.esm-bundler.js:154
    xe runtime-core.esm-bundler.js:384
runtime-core.esm-bundler.js:225:16
    Zt runtime-core.esm-bundler.js:225
    Xt runtime-core.esm-bundler.js:203
    Ue runtime-core.esm-bundler.js:958
    update runtime-core.esm-bundler.js:4359
    n reactivity.esm-bundler.js:42
    Qt runtime-core.esm-bundler.js:154
    xe runtime-core.esm-bundler.js:384
```

**Comment by nanu-c** [comment]
I think this is solved by https://github.com/nanu-c/axolotl/pull/533 can you try?

**Comment by raphj** [comment]
It doesn't, my version of axolotl already had this fix. It's not `devices` which is undefined / null here, it is a particular `device` in this which which is.

**Comment by raphj** [comment]
To be more specific, the crash happens when trying to access the `id` property of the undefined device in this chunk of code:


```js
      <div v-for="device in devices" :key="device.id" class="row device">
        <div v-if="device.id != 0" class="col-10"> 
```

Maybe a cleaner fix than mine would be to filter undefined devices out of `devices` with something like `devices = devices.filter(d => d)`?

But that would hide the issue.

**Comment by raphj** [comment]
Actually, I don't reproduce anymore. I guess I messed up something while investigating the bug.

I guess we can close this issue, I'll reopen if I reproduce it again. Sorry for having wasted your time!
