### ISSUE TITLE
State of Axolotl

### ISSUE THREAD

**Issue by julianfairfax** [nanu-c/axolotl#541]
I've used Axolotl as my main Signal client on my PinePhone and I'm making this issue to report my findings in terms of features that are missing and bugs that I found. I'm not sure if it would be productive to open a separate issue for each of the features that are missing and each of the bugs that I found but if you'd like I can do that. Missing features or bugs that have already been reported are linked in my lists. Thank you for all the work on this wonderful app and hopefully it will continue to get better!

Missing features
- Blocking contacts #578
- Receiving typing indicators #579
- Syncing read receipts to the desktop client #580
- Receiving profile photos #87
- Changing profile settings #8
- Deleting messages #581
- Deleting contacts #530

Some more
- Groupv2 moderation
- Show Groupv2 Userlist
- Join Groupsv2 by Link
- Accept Groupsv2 invitation
- Verify contacts and indicate when the key of verified contacts changes
- Unidentified sender
- Payments
- Sending voice notes

Bugs
- Linking more than one device does not work #529

**Comment by nanu-c** [comment]
Thanks for the list I want to add some more :)

* Groupv2 moderation
* Show Groupv2 Userlist
* Join Groupsv2 by Link
* Accept Groupsv2 invitatation
* Verify contacts and indicate when the key of verified contacts changes
* Unidentified sender
* Payments
* Sending voice notes

Now some hints why the current state is like that
* what do you mean by follow the system theme? Axolotl is a web app that runs on windows/ubuntu touch/Mobian/Unity/Gnome3/KDE/OsX. Dark mode is implemented.
* Axolotl has no access to the microphone on ubuntu touch, so it doesn't make sense to implement that feature.
* Deleting chats is in the works https://github.com/nanu-c/axolotl/pull/537
* Deleting can be done by longpressing the contact in the contact list
* Quotes and Reactions need an refactor of the message database, so it's a rather big task.
* Syncing contacts from the address book depends on the OS. For ubuntu touch, contact sync is not allowed at all except by exporting through content hub and I am not using mobian. So here a PR is really appreciated.
* Importing contacts thorugh a vcf file should work, at least it does through Ubuntu Touch.

**Comment by julianfairfax** [comment]
> Thanks for the list I want to add some more :)
> 
>     * Groupv2 moderation
> 
>     * Show Groupv2 Userlist
> 
>     * Join Groupsv2 by Link
> 
>     * Accept Groupsv2 invitation
> 
>     * Verify contacts and indicate when the key of verified contacts changes
> 
>     * Unidentified sender
> 
>     * Payments
> 
>     * Sending voice notes
> 
I will add those
> 
> Now some hints why the current state is like that
> 
>     * what do you mean by follow the system theme? Axolotl is a web app that runs on windows/ubuntu touch/Mobian/Unity/Gnome3/KDE/OsX. Dark mode is implemented.
> 
I mean if I change my GTK theme to a dark one, Axolotl's dark mode isn't turned on as a result.
>     * Axolotl has no access to the microphone on ubuntu touch, so it doesn't make sense to implement that feature.
> 
Would you happen to know if it does on Mobian? And do you mean that it cannot or that you haven't implemented that permission? If it's not possible I will remove both call features but there should be a way to use the microphone, although I think not the camera.
>     * Deleting chats is in the works [Add delete function in chat page #537](https://github.com/nanu-c/axolotl/pull/537)
> 
I will link that
>     * Deleting contacts can be done by longpressing the contact in the contact list
> 
I don't think that worked when I tried.
>     * Quotes and Reactions need a refactor of the message database, so it's a rather big task.
> 
I will remove those since they're not that important.
>     * Syncing contacts from the address book depends on the OS. For ubuntu touch, contact sync is not allowed at all except by exporting through content hub and I am not using mobian. So here a PR is really appreciated.
> 
I'm using Signal on my Android device and can't use it on both so I can't really do that, but I will remove it.
>     * Importing contacts through a vcf file should work, at least it does through Ubuntu Touch.
It doesn't on Mobian, at least when I try it.

**Comment by julianfairfax** [comment]
Closed since I've decided to just use the Signal Desktop app and try to improve it.

**Comment by julianfairfax** [comment]
Reopening since I'm using Axolotl again and these points are still valid.

**Comment by julianfairfax** [comment]
I've made new issues and linked them here.
