### ISSUE TITLE
[BUG] Verify Identity broken

### ISSUE THREAD

**Issue by Blackoverflow** [nanu-c/axolotl#548]
### Description

The Feature "Verify Identity" is broken

### Steps to Reproduce

1. Enter a chat
2. Cklick "Show identity" in the menu.

**Expected behavior:**
A big qr-code and 12 groups of 5 digits representing the Safety Numbers are visible.

**Actual behavior:**
![screenshot20210822_214645438](https://user-images.githubusercontent.com/55155049/130369217-5f408ca9-ce73-4b74-bb15-5b2790460b66.png)

#### Versions

Axolotl 1.0.1.1

#### Device
Volla Phone

#### Link to Debug Log
I haven't found the relevant part yet. I'll add it later.

**Comment by Danfro** [comment]
Confirmed on Xperia X devel. Also the qr code displayed seems to be exactly the same for everyone.

**Comment by Blackoverflow** [comment]
The corresponding log message is `[axolotl] identity information  unknown contact ID <phone number>`.
It is thrown in https://github.com/signal-golang/textsecure/blob/9a87085a8b808001bfbd525c4068bd9e2a54b1e7/store.go#L252
How did the storage of identities changed? I guess they are now referenced by UUID instead of by phone number?

**Comment by Blackoverflow** [comment]
All official implementations still use `FINGERPRINT_VERSION 0`:
- https://github.com/signalapp/libsignal-protocol-java/blob/fde96d22004f32a391554e4991e4e1f0a14c2d50/java/src/main/java/org/whispersystems/libsignal/fingerprint/NumericFingerprintGenerator.java#L22
- https://github.com/signalapp/libsignal-protocol-rust/blob/fa113a571eacfd46df03bbd3d974a05e6ffb7ce4/src/fingerprint.rs#L164
- https://github.com/signalapp/libsignal-client/blob/8fc9361647027a5e0cb349ae7d5d29211a81d4d7/rust/protocol/src/fingerprint.rs#L169
- https://github.com/signalapp/libsignal-protocol-c/blob/3a83a4f4ed2302ff6e68ab569c88793b50c22d28/src/fingerprint.c#L10

I hope that means they didn't change it and our algorithm is still valid.

**Comment by Blackoverflow** [comment]
It may be enough to change this line
https://github.com/nanu-c/axolotl/blob/011cf98b62b8891a48bd0584ae79e5bd3d8f0482/app/webserver/webserver.go#L419
 to `fingerprintNumbers, fingerprintQRCode, err := textsecure.GetFingerprint(s.UUID)`.

But i don't know if all identiyKeys are now referenced by UUID or if old contacts are still referenced by phone number.

**Comment by nuehm-arno** [comment]
It's working on Mobian with v1.0.7...
