### ISSUE TITLE
No indication of network failure

### ISSUE THREAD

**Issue by lionelb123** [nanu-c/axolotl#55]
### Description Messages 'sent' during network problems do not generate an alert

[Description of the issue] I sent a couple of messages when wifi was shown as connected but not actually functioning. Those messages got a single tick and were marked 'a very long time ago'. My impression was that those accounts had broken. With network running again, messages on those accounts sent normally.

### Steps to Reproduce 

1. [First Step] Wifi handshake is incomplete
2. [Second Step] Send a message in the normal way
3. [and so on...]

**Expected behavior:** [What you expect to happen] Where there is a failure in the network connection and the message is not actually sent, I would expect something like a red ! and a message "network error - message not sent"

**Actual behavior:** [What actually happens] The message has one tick, suggesting that it sent. It is not sent, when network connection resumes

**Reproduces how often:** [What percentage of the time does it reproduce?]

#### Versions 0.4.1

Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`

#### Device  BQ FHD Frieza
What device

#### Link to Debug Log
Please provide the link generated by `Settings->Advanced-> Submit Debug Log`

#### Else
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by nanu-c** [comment]
solved in https://github.com/nanu-c/axolotl/commit/2c5f6abb7ccd6abc9bfc3c089b9624ad0afb5d25
