### ISSUE TITLE
Be able to rename contacts

### ISSUE THREAD

**Issue by raphj** [nanu-c/axolotl#563]
**Is your feature request related to a problem? Please describe.**

It is a feature request. I'd like to be able to rename a contact. It is actually possible today by adding a new contact and entering the number of the existing contact one want to rename. I tried hoping that it will work and it worked but having an obvious way to do it would be nice.

**Describe the solution you'd like**

Having an option "Rename contact" in the hamburger menu would be fine. Or a "pen" icon somewhere.

**Describe alternatives you've considered**

None

**Additional context**

None

----

No promise here, but if we decide how this feature should be solved UI/UX wise and I find some time, I can try a merge request.

**Comment by nuehm-arno** [comment]
Should be resolved with v1.0.5... Please confirm and close the issue.

**Comment by raphj** [comment]
Hello @nuehm-arno 

It does not seem to work. I just installed axolotl 1.0.5-1 downloaded here: https://github.com/nuehm-arno/axolotl-mobian-package/blob/main/axolotl_1.0.5-1_arm64.deb

I run axolotl this way:

    /usr/bin/axolotl --host 0.0.0.0 -e server -axolotlWebDir /usr/share/axolotl/axolotl-web/dist

When I click on the edit icon and then on any contact, I get the following error on Firefox:

```
TypeError: t is null
    contactClick Contacts.vue:188
    2 Contacts.vue:74
```

Contact.vue:188 is this part of the code, I would guess `t` is `contact` 

    contactClick(contact) {
      if (!this.showActions) {
        if (this.validateUUID(contact.UUID))
          this.$store.dispatch("createChat", contact.UUID);
      } else {
        this.editContactId = contact.Tel;
      }
    },

Contact.vue:74 seems to be the ` @click="contactClick(contact)"` in this chunk:

      <div class="row chat-entry">
        <div
          :class="'avatar col-3 avatar ' + checkForUUIDClass(c)"
          @click="contactClick(c, i)"
        >
          <div class="badge-name">{{ c.Name[0] + c.Name[1] }}</div>
        </div>
        <div
          class="meta col-9"
          data-long-press-delay="500"
          @click="contactClick(contact)"
          @long-press="showContactAction(contact)"
        >
          <p class="name">{{ c.Name }}</p>
          <p class="number">{{ c.Tel }}</p>
        </div>
      </div>
    </div>

I am clicking with a mouse from a computer.

Just as I am pasting these snippets, I realize that `contact` should probably read `c`, because `c.Name` and `c.Tel` work, since I can see the names and the numbers of my contacts in these pages.

**Comment by raphj** [comment]
For the record, it's here in the latest commit of `main` to this date: https://github.com/nanu-c/axolotl/blob/677869983758b4966661e8766edaee705f5a6dca/axolotl-web/src/pages/Contacts.vue#L74-L75

**Comment by nanu-c** [comment]
We have introduced a new icon in the contact list for editing the contact. This a step to proper profile support and i think it closes this.

**Comment by raphj** [comment]
I confirm I'm now able to rename contacts.

At first I was confused by the + button hiding the wrench of the last contact in the list, but the wrench is not actually a button and a toolbar  to manage the selected contact appears.

I'd suggest to remove the wrench but it works as-is.

**Comment by raphj** [comment]
Mhm, actually the wrench is the button. So be aware that the + button on the list may hide the wrench button of the last contact on some screens.
