### ISSUE TITLE
[BUG] App crashes on canceling contact import

### ISSUE THREAD

**Issue by jonnius** [nanu-c/axolotl#567]
### Description

App crashes on canceling contact import

### Steps to Reproduce

1. Select contact import to get to content hub page
2. Cancel content hub page

**Expected behavior:** Get back to app

**Actual behavior:** App crashes

#### Versions

1.0.4

#### Device
Xperia X / Desktop Mode

#### Link to Debug Log
FATA[2021/09/19 12:05:33] open canceld: no such file or directory

**Comment by nanu-c** [comment]
closed by #758
