### ISSUE TITLE
[BUG] Incoming messages not shown in axolotl

### ISSUE THREAD

**Issue by DirkMetzler** [nanu-c/axolotl#569]
### Description

Thank you for the new release 1.0.5 with which I was now able to register on signal and also to connect to signal-desktop.
The problem is now that don't see incoming messages in the axolotl app on my Fairphone 2. I receive these messages however in the connected signal-desktop app on my Linux computer. In the axolotl app I see messages that I sent to others, no matter whether I sent them from my phone with axolotl or with signal-desktop.

#### Versions

Axolotl Beta 1.0.5
Ubutu Touch 16.04 (OTA-19)
(both updated today)

#### Device
Fairphone 2

#### Link to Debug Log
Surprisingly, a log file with a name like ~/.cache/upstart/application-click-textsecure.nanuc_textsecure*.log does not exist on my phone. (There is a file application-click-textsecure.nanuc_textsecure_0.4.6.log  in ~/Downloads on the phone, but the lines in that file refer to the date 2019/09/04)

Many thanks and best wishes,
Dirk

**Comment by Flaburgan** [comment]
Hello @DirkMetzler and thank you for taking time to report an issue. Unfortunately, without logs file, there isn't much we can do. Could you please do a search for "textsecure" and see if anything pops out somewhere?

**Comment by DirkMetzler** [comment]
Dear @Flaburgan,

thank you for your reply. Below is what I got with
find ~ -name '*textsecure*'
(I guess the log file in Download I is from somebody else and I had downloaded it unintentionally when I searched for a solution in some forum)

/home/phablet/Downloads/application-click-textsecure.nanuc_textsecure_0.4.6.log
/home/phablet/.config/textsecure.nanuc
/home/phablet/.cache/url-dispatcher/click-urls/textsecure.nanuc_textsecure_1.0.5.url-dispatcher
/home/phablet/.cache/ubuntu-app-launch/desktop/textsecure.nanuc_textsecure_1.0.5.desktop
/home/phablet/.cache/textsecure.nanuc
/home/phablet/.local/share/click/hooks/desktop/textsecure.nanuc_textsecure_1.0.5.desktop
/home/phablet/.local/share/content-hub/textsecure.nanuc_textsecure_1.0.5
/home/phablet/.local/share/ubuntu-push-client/helpers/textsecure.nanuc_push_1.0.5.json
/home/phablet/.local/share/applications/textsecure.nanuc_textsecure_1.0.5.desktop
/home/phablet/.local/share/textsecure.nanuc

**Comment by Flaburgan** [comment]
but you have nothing in `.upstart`? Can you look if you find something there which could be from Axolotl?

**Comment by DirkMetzler** [comment]
in .cache/upstart I have the unzipped log files

.cache/upstart/dbus.log
.cache/upstart/dekkod-notify.log
.cache/upstart/unity8.log

and the gzipped log files (where I show only the latest, that is not 1-6 if 7 exist):

.cache/upstart/address-book-updater.log.7.gz
.cache/upstart/application-click-com.ubuntu.terminal_terminal_1.0.2.log
.cache/upstart/application-failed.log.7.gz
.cache/upstart/bluez-mpris-proxy.log.7.gz
.cache/upstart/ciborium.log.7.gz
.cache/upstart/click-user-hooks.log.7.gz
.cache/upstart/copy-browser-files.log.7.gz
.cache/upstart/dbus.log.7.gz
.cache/upstart/dekkod-notify.log.7.gz
.cache/upstart/gnome-keyring.log.7.gz
.cache/upstart/indicator-messages.log.7.gz
.cache/upstart/indicator-network.log.7.gz
.cache/upstart/indicator-network-secret-agent.log.2.gz
.cache/upstart/indicator-session.log.3.gz
.cache/upstart/indicator-sound.log.7.gz
.cache/upstart/maliit-server.log.7.gz
.cache/upstart/media-hub.log.7.gz
.cache/upstart/mediascanner-2.0.log.7.gz
.cache/upstart/msyncd.log.7.gz
.cache/upstart/mtp-server.log
.cache/upstart/mtp-server.log.7.gz
.cache/upstart/nuntium.log.7.gz
.cache/upstart/ofono-setup.log.7.gz
.cache/upstart/osmscout-server.log.1.gz
.cache/upstart/pulseaudio-trust-stored.log.7.gz
.cache/upstart/ssh-agent.log.7.gz
.cache/upstart/sync-monitor.log.7.gz
.cache/upstart/telephony-service-indicator.log.7.gz
.cache/upstart/tone-generator.log.7.gz
.cache/upstart/ubuntu-location-service-trust-stored.log.7.gz
.cache/upstart/ubuntu-push-client.log.7.gz
.cache/upstart/unity8.log.7.gz
.cache/upstart/untrusted-helper-type-end-push-helper.log.7.gz
.cache/upstart/url-dispatcher.log.2.gz
.cache/upstart/url-dispatcher-update-system.log.1.gz
.cache/upstart/usensord.log.7.gz

**Comment by DirkMetzler** [comment]
Now I have a log file. Problem was before that I did not understand that the log files are deleted when I close the axolotl app, sorry for my confusion. 

below I pasted some obvious error messages from the log file. I removed some uid, pid and other numbers due to putative privacy issues. (If you need the full log file, could you please give me a hint what data besides telephone numbers I should remove?)

[31mERRO[0m[0000] dial tcp [::1]:9081: connect: connection refused 
[31mERRO[0m[0000] [axolotl-crayfish-ws] Failed to start listening  [31merror[0m="dial tcp [::1]:9081: connect: connection refused"
[...]
[36mINFO[0m[2021/09/24 14:45:37] [axolotl-qml] [ [HERE I REMOVED SOME NUMBERS] :ERROR:file_path_watcher_linux.cc(71)] Failed to read /proc/sys/fs/inotify/max_user_watches 
[...]
[36mINFO[0m[2021/09/24 14:45:37] [axolotl-qml] error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.119\" (uid=[REMOVED] pid=[REMOVED] comm=\"/usr/lib/qt5/bin/qmlscene --scaling guis/qml/ut/Ma\") interface=\"com.canonical.libertine.Service.Operations\" member=\"list\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=[REMOVED] pid=[REMOVED] comm=\"/usr/bin/python3 /usr/bin/libertined \")" 
[...]
[36mINFO[0m[2021/09/24 14:45:37] [axolotl-qml] error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.119\" (uid=[REMOVED] pid=[REMOVED] comm=\"/usr/lib/qt5/bin/qmlscene --scaling guis/qml/ut/Ma\") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"last_error\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=[REMOVED] pid=[REMOVED] comm=\"/usr/bin/python3 /usr/bin/libertined \")" 
[36mINFO[0m[2021/09/24 14:45:37] [axolotl-qml] lastError - no arguments?      
[36mINFO[0m[2021/09/24 14:45:37] [axolotl-qml] error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.119\" (uid=[REMOVED] pid=[REMOVE] comm=\"/usr/lib/qt5/bin/qmlscene --scaling guis/qml/ut/Ma\") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"result\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=[REMOVED] pid=[REMIVED] comm=\"/usr/bin/python3 /usr/bin/libertined \")" 
[36mINFO[0m[2021/09/24 14:45:37] [axolotl-qml] lastError - no arguments?      
[...]

[36mINFO[0m[2021/09/24 14:45:37] [axolotl-qml] qml: MainUt_QMLTYPE_29(0x24ff00)"Axolotl": In Ubuntu.Components 1.3, the use of Page.title, Page.flickable and Page.head is deprecated. Use Page.header and the PageHeader component instead. 
[36mINFO[0m[2021/09/24 14:45:37] [axolotl-qml] file:///opt/click.ubuntu.com/textsecure.nanuc/1.0.5/guis/qml/ut/MainUt.qml:167:7: Unable to assign [undefined] to QObject*
file:///opt/click.ubuntu.com/textsecure.nanuc/1.0.5/guis/qml/ut/MainUt.qml:226: TypeError: Cannot read property 'message' of null 
[36mINFO[0m[2021/09/24 14:45:37] [axolotl-qml] library "/vendor/lib/egl/libGLESv2S3D_adreno.so" not found 
[36mINFO[0m[2021/09/24 14:45:38] [axolotl-qml] [[REMOVED SOME NUMERS]:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid [REMOVED]: Permission denied (13) 
[...]

[31mERRO[0m[2021/09/24 14:45:39] [axolotl-ws] wsReader  websocket: close 1001 (going away) 

[31mERRO[0m[2021/09/24 14:45:40] [textsecure] Failed to handle received message  [31merror[0m="not implemented message type unindentified sender [ [LOTS OF NUMBERS REMOVED..; THERE WERE LOTS OF ERROR MESSAGES OF THIS KIND]

[31mERRO[0m[2021/09/24 14:46:26] [axolotl-ws] wsReader panic occurred: runtime error: invalid memory address or nil pointer dereference

**Comment by TabletopsAndAnvils** [comment]
I'm experiencing the same thing. I linked my mac desktop client to axolotl just fine, any messages I type in the axolotl client show up on the mac and vice versa, however I am not getting recipients response on the axolotl client and don't believe my recipient is getting the messages from axolotl either -wait, confirmed. They're getting "Chat session refreshed" in their desktop client instead of my message. Even more interesting, he can see my axolotl sent messages on his iphone client but neither messages sent from his desktop or iphone are appearing in my axolotl.

![signal-2021-09-24-125457_001](https://user-images.githubusercontent.com/76455772/134713256-0799fcab-e54e-4d01-a7c3-61d925a20ab7.png)
.

**Comment by DirkMetzler** [comment]
Perhaps I should add to bits of information:
1) When I send messages from the axolotl app on my phone to "notes", that is, the chat in which I am the only participant, these messages just disappear and are neither shown in the axolotl app nor in signal-desktop. Perhaps some of the log file error messages show in my previous post come from these errors.
2) Before I registered with the axolotl app, I had a signal registration that I accessed with signal-desktop. The contacts and chats of this earlier registration are still shown in signal-desktop.

**Comment by DirkMetzler** [comment]
Hi, this issue is still labeled with "needs more information". Is this still true or were the log file error messages that I sent a few days ago what you needed?

**Comment by trollordragon** [comment]
I have the same issue on my pinephone, running axolotl 1.0.5 (using a repackaged version of @nuehm-arno  .deb for mobian) on Manjaro arm. I started axolotl from terminal, when receiving a message I get the "not implemented message type unindentified sender" error message and several lines of numbers (see above). Beside that, the terminal output shows no other error messages and axolotl connected to the websocket and ping messages are being sent.
I was able to connect signal desktop to axolotl. The messages I sent from signal-desktop are shown on the pinephone but not the messages I receive. Beside that, I can not start new conversations, as it is not possible to add a contact (already reported here: https://github.com/nanu-c/axolotl/issues/381)

**Comment by forfuks** [comment]
I also have the same issues .signal works fine on my laptop but no messages recieved on phone which is a redmi 7

**Comment by kpenfound** [comment]
Similar to @trollordragon , I get `[textsecure] Failed to handle received message error="not implemented message type unidentified sender (and then a byte array)"` when I should receive a message, which looks to come from here: https://github.com/signal-golang/textsecure/blob/master/textsecure.go#L633
I'll do some more debugging to see if I can turn up anything useful

**Comment by DirkMetzler** [comment]
Many thanks for release 1.0.8, with which the problem seems to be solved! 
Shall we close the issue or does someone still has this problem?

**Comment by Flaburgan** [comment]
Yes this should be solved, I'm closing the issue now, please comment if anyone still experiences this, I'll re-open.
