### ISSUE TITLE
Deleting selected messages broken

### ISSUE THREAD

**Issue by 1ploss** [nanu-c/axolotl#57]
### Description

It is not possible to delete selected messages.

### Steps to Reproduce

1. Select at least one message in any conversation by long pressing on it.
2. Select "Delete message" from the hamburger menu.

**Expected behavior:**
A confirmation pop-up appears.

**Actual behavior:**
No reaction.
The following message gets logged:
2019/03/07 14:45:17 DialogPage.qml:178: file:////opt/click.ubuntu.com/textsecure.nanuc/0.4.1/qml/phoneui/ui/DialogPage.qml:178: TypeError: Property 'deleteSelected' of object MultipleSelectionListView_QMLTYPE_42_QML_123(0x9143b8f8) is not a function 

**Reproduces how often:** 100%

#### Versions
0.4.1
#### Device
Nexus 5

**Comment by yo-k** [comment]
It's kind of fixed because you don't get a dialog to delete a message in a conversation anymore :-)
We have to check it again when the dialog is back. Until that keep this ticket open.

**Comment by olof-nord** [comment]
This issue is fixed. Tested with axolotl v0.9.9.
