### ISSUE TITLE
[BUG] Groups/Chats with self-destruct timer are displayed out of alignment

### ISSUE THREAD

**Issue by nuehm-arno** [nanu-c/axolotl#575]
### Description

Since v1.0.5 opening a group with self-destruct timer results in a shifted screen. Only the input field and the violet timer picture fragments are shown (see attached picture). Scrolling down brings back messages and header. Screolling up shifts the screen again.

### Steps to Reproduce

1. Tap on a group with self-destruct timer
2. See shifted screen
3. Scroll down
4. See messages and header

**Expected behavior:**
Group is shown as groups without self-destruct timer.

**Actual behavior:**
Shifted screen.

#### Versions
v1.0.5

#### Device
Mobian@Pinephone

#### Link to Debug Log
No error logs found.

![shifted_screen](https://user-images.githubusercontent.com/29338682/135247234-6de33f57-d72e-4046-ac7c-d8c8710a30c9.jpg)

**Comment by Blackoverflow** [comment]
I experience this issue on Ubuntu Touch @ VollaPhone. It's not Mobian or Pinephone specific.

**Comment by nuehm-arno** [comment]
Title changed - Thanks for confirming.
