### ISSUE TITLE
Messages with multiple pictures - Unknown Message Content

### ISSUE THREAD

**Issue by 1ploss** [nanu-c/axolotl#58]
### Description

Someone sent me a message with more than one picture. I didn't know this was a feature. This client does not know either.
The message never appeared in the conversation.
Since than, the following error appears in the logs:                                                  
ERRO[2019/03/07 17:05:05] Unknown message content received                        

I think the client never confirms that the message arrived, so the server sends it again and again.

### Steps to Reproduce

1. Have someone sent you a message with more than one picture.

**Expected behavior:**
Find a message within the conversation saying that I got a message type that is not supported or a message containing the pictures.

**Actual behavior:** 
No message appears within the conversation.
An error is logged multiple times per day.
I suspect the message gets fetched once per logged error, draining data and battery.

**Reproduces how often:**

At least 4 messages with multiple pictures were sent to me. Non of them appeared in the conversations (one group and one 1-to-1).
Since then said errors appear in the logs.

#### Version

0.4.1

#### Device
Nexus 5

**Comment by nanu-c** [comment]
this is solved now

**Comment by Alter2020** [comment]
Receiving multiple pictures/photos in one message does not work yet on my device (Nexus 5, RC, Axolotl 0.8.7). At least, not completely. When someone shares photos via the iOS Photo app, I receive them all. If that same person selects the same photos in iOS Signal I receive a message with 1 photo that is shown multiple times. If someone sends me photos from Android Signal, I always receive 1 photo multiple times, regardless of the way it's sent: via Google Photos or Signal.
