### ISSUE TITLE
implement import contacts and groups to signal desktop

### ISSUE THREAD

**Issue by fabrei** [nanu-c/axolotl#63]
### Description

if it try to import my contacts to the signal desktop app it does not work in case of a timeout. i already opened an [issue at the signal desktop app repo](https://github.com/signalapp/Signal-Desktop/issues/3397). it is an issue in the ut app, because the signal app changed their api. in the issue you also find the debug logs of the desktop and ut app.

### Steps to Reproduce

1. open signal desktop app
2. file > preferences > import now
3. waiting until the message "Import failed. Make sure your computer and your phone are connected to the internet." occurs

**Expected behavior:** the imports are synchronised with the ut app.

**Actual behavior:** a timeout occurs 

**Reproduces how often:** 100% now..my last import was at the end of 2018..

#### Versions
signal on ut 16.04 ota 9: 0.3.14
signal on debian 9: 1.25.1

#### Device
oneplusone bacon 

#### Link to Debug Log
[desktop app](https://gist.githubusercontent.com/fabrei/3ed1e6bb22c849e23ee1a168277063af/raw/337df7a73d3a813486aa3b75e86b3557d6d6e6b4/signal-desktop.log)
[signal ut app](https://gist.githubusercontent.com/fabrei/09b303875cb318c6e3d32047a4255212/raw/d9ad5c67c68c69234a49af2b59392ed9e51fe4fe/signal-ut.log)

**Comment by nanu-c** [comment]
i think the api changed for that.

**Comment by ruedigerkupper** [comment]
Confirming: Import to signal desktop fails in the described way.

**Comment by fabrei** [comment]
is this repository still alive, so that i can expect that it will be fixed in the near future?

**Comment by nanu-c** [comment]
this repository is alive but it will not be fixed in the near future because quite some parts have to be rewritten before minor bugs like are solved

**Comment by jensfriisnielsen** [comment]
I have a huge need for this as well. Basically this functionality is required to have signal desktop app integration at all. Without contacts how can you use it? I presume most people prefer the desktop version (and keyboard) for chatting if possible even with a fully featured and functional mobile app.

**Comment by Blackoverflow** [comment]
Signal Desktop reports the following error:
Uncaught (in promise) Error: Failure: Ask sender to update Signal and resend.
    at MessageReceiverInner.downloadAttachment (/opt/Signal/resources/app.asar/ts/textsecure/MessageReceiver.js:1118)

As far as I understand right now, the contacts are packaged and sent as attachment.
Sending attachments has two parts:
1. Uploading the attachment (encrypted)
2. Sending a message containing information from where to download that attachment.

I guess that part 1 is broken right now. Signal Desktop gets information where the attachment should be. But there is no attachment to download.

**Comment by jensfriisnielsen** [comment]
> I also can confirm this bug still existing with Axolotl version 0.8.2. Is there a chance to add the contacts in the Desktop app of Signal manually?

I haven't found it in the Linux version yet

**Comment by nanu-c** [comment]
solved in 0.8.6
