### ISSUE TITLE
[BUG] Unable to receive message after failed photo upload.

### ISSUE THREAD

**Issue by pparent76** [nanu-c/axolotl#639]
Hi,

Just wanted to mention the following bug that I'm experiencing right now:

-I made a fresh install of signal with axolotl
-I sent messages to a friend, he received them.
-I tried to upload a photo but it failed beacause I was in a poor network area, and kept hanging forever.
-Now I cannot receive messages, but the app still syncs with messages that I send myself from signal desktop (but not with those I receive).
-I tried deleting the conversation with photos that do not upload but it did not change anything.

I'm available to make any test you would find useful.

**Comment by flaun** [comment]
Are you still confronted to this bug?
Guess I have a similiar problem:
First I was not able to send or receive messages to one of my contacts.
So I decided to reinstall the whole app inclusive deleting registration, cache and config.
Afterwards I couldn't receive any other message. And as it still not works to import concacts (or at least most of the time) I'm not able to start new chats.
Once it was possible, than recipients got my messages but I didn't get anything from them!

I really need. Axolotl is very important for me.....
This is my actual logfile: 
[application-click-textsecure.nanuc_textsecure_1.0.8.log](https://github.com/nanu-c/axolotl/files/7641502/application-click-textsecure.nanuc_textsecure_1.0.8.log)

**Comment by pparent76** [comment]
@flaun I reinstalled since then. It's hard to do some testing and constantly bother friends with it to know weather it works, when it seems far from stable enough to be used persistently in real life case.

**Comment by nanu-c** [comment]
#985 Has to reimplement attachment handling, so closing this.
