### ISSUE TITLE
[BUG] Can't recieve messages anymore

### ISSUE THREAD

**Issue by flaun** [nanu-c/axolotl#641]
### Description

First I was not able to send or receive messages to one of my contacts.
So I decided to reinstall the whole app inclusive deleting registration, .cache and .config.
Afterwards I couldn't receive any other message. And as it still not works to import contacts (or at least most of the time) I'm not able to start new chats.
Once it was possible, than recipients got my messages but I didn't get anything from them!
Right know I still get messages from groups. Nothing else works.

I really need help. Axolotl is very important for me.....

**Expected behavior:** Receive messages. Be able to reply. Add contacts

#### Versions

Axolotl 1.0.8

#### Device
Meizu MX4 (daily driver) - RC-Channel

#### Link to Debug Log
[application-click-textsecure.nanuc_textsecure_1.0.8.log](https://github.com/nanu-c/axolotl/files/7641537/application-click-textsecure.nanuc_textsecure_1.0.8.log)

**Comment by flaun** [comment]
After trying lots of time I was able to add contact.
Then I created a new chat and sent a message. The other person receipt my message. I didn't get the response!
Tried it with different contacts.
This are the logs (maybe more interesting than the others above!) 

[application-click-textsecure.nanuc_textsecure_1.0.8 (2).log](https://github.com/nanu-c/axolotl/files/7643968/application-click-textsecure.nanuc_textsecure_1.0.8.2.log)

I realy hope someone can help me.....
.

**Comment by flaun** [comment]
Update: After completely wiping and reinstalling the whole ubuntu touch OS I hoped to get a working axolotl app again. But no, still the same problem. Can't receive any message!
Via Signal desktop liked to axolotl everything works fine!
Here the new logs:
[application-click-textsecure.nanuc_textsecure_1.0.8.log](https://github.com/nanu-c/axolotl/files/7656591/application-click-textsecure.nanuc_textsecure_1.0.8.log)

It's very frustrating. Seems I'm the only person facing this problem!
Still hoping someone could help me...

**Comment by nanu-c** [comment]
Hey flaun, thanks for reporting, the interesting part is this one `GET /v2/keys/+XXXXXXXXXX/1 404 `, this shouldn't use the phone number anymore. Can you try to delete that contact + receive a message prior to sending one? Further the log doesn't show any abnormalities and also the log doesn't show a receiving message at all. So don't know where to start.

**Comment by flaun** [comment]
hey nanu-c,
thanks for answering.
Right now I'm not able to add any contacts after reinstalling everything.
I tried with different persons to get a message, but still don't receive anything.
Even tried it with persons I never wrote so far....
Any further idea what I could do?

**Comment by nanu-c** [comment]
that sounds like you are hitting a rate limit at the moment or so. What shows the contacts page? No contacts or grey contacts or blue contacts?

**Comment by flaun** [comment]
In the past i head blue contacts. But as I mentioned: adding contacts fails right no:
contacts will be imported, come back later. Than nothing happens!

After deleting registration and installing the app new, I was able to import contacts after trying a few times. When other tried to send me a message I didn't get anything. But they got my message!

Here are the logs, maybe this helps

`[31mERRO[0m[2021/12/02 16:51:01] dial tcp [::1]:9081: connect: connection refused 
[31mERRO[0m[2021/12/02 16:51:01] [textsecure-crayfish-ws] Failed to start listening  [31merror[0m="dial tcp [::1]:9081: connect: connection refused"
[37mDEBU[0m[2021/12/02 16:51:02] [axolotl] send message to  1                 
[37mDEBU[0m[2021/12/02 16:51:02] getPreKeys 750cfc86-0027-49a7-8447-f3638db88132 1 
[37mDEBU[0m[2021/12/02 16:51:03] [textsecure] GET /v2/keys/750cfc86-0027-49a7-8447-f3638db88132/1 200 
[37mDEBU[0m[2021/12/02 16:51:03] [textsecure] PUT /v1/messages/750cfc86-0027-49a7-8447-f3638db88132 200 
[37mDEBU[0m[2021/12/02 16:51:03] [textsecure] SendMessageResponse: {NeedsSync:false Timestamp:1638460262503} 
[37mDEBU[0m[2021/12/02 16:51:03] [axolotl] SendMessage 750cfc86-0027-49a7-8447-f3638db88132 1638460262503 
[37mDEBU[0m[2021/12/02 16:51:03] [axolotl-ws] UpdateMessageHandlerWithSource  1 1638460262503 
[37mDEBU[0m[2021/12/02 16:51:03] [textsecure-crayfish-ws] websocket connecting to crayfish-server 
[31mERRO[0m[2021/12/02 16:51:03] dial tcp [::1]:9081: connect: connection refused 
[31mERRO[0m[2021/12/02 16:51:03] [textsecure-crayfish-ws] Failed to start listening  [31merror[0m="dial tcp [::1]:9081: connect: connection refused"
[37mDEBU[0m[2021/12/02 16:51:05] [textsecure-crayfish-ws] websocket connecting to crayfish-server 
[31mERRO[0m[2021/12/02 16:51:05] dial tcp [::1]:9081: connect: connection refused 
[31mERRO[0m[2021/12/02 16:51:05] [textsecure-crayfish-ws] Failed to start listening  [31merror[0m="dial tcp [::1]:9081: connect: connection refused"
[37mDEBU[0m[2021/12/02 16:51:07] [textsecure-crayfish-ws] websocket connecting to crayfish-server 
[31mERRO[0m[2021/12/02 16:51:07] dial tcp [::1]:9081: connect: connection refused 
[31mERRO[0m[2021/12/02 16:51:07] [textsecure-crayfish-ws] Failed to start listening  [31merror[0m="dial tcp [::1]:9081: connect: connection refused"
[36mINFO[0m[2021/12/02 16:51:09] [axolotl-qml] QObject::startTimer: Timers cannot be started from another thread 
[37mDEBU[0m[2021/12/02 16:51:09] [textsecure-crayfish-ws] websocket connecting to crayfish-server 
[31mERRO[0m[2021/12/02 16:51:09] dial tcp [::1]:9081: connect: connection refused 
[31mERRO[0m[2021/12/02 16:51:09] [textsecure-crayfish-ws] Failed to start listening  [31merror[0m="dial tcp [::1]:9081: connect: connection refused"
[37mDEBU[0m[2021/12/02 17:06:30] [textsecure-crayfish-ws] websocket connecting to crayfish-server 
[31mERRO[0m[2021/12/02 17:06:30] dial tcp [::1]:9081: connect: connection refused 
[31mERRO[0m[2021/12/02 17:06:30] [textsecure-crayfish-ws] Failed to start listening  [31merror[0m="dial tcp [::1]:9081: connect: connection refused"
[37mDEBU[0m[2021/12/02 17:06:32] [textsecure-crayfish-ws] websocket connecting to crayfish-server 
[31mERRO[0m[2021/12/02 17:06:32] dial tcp [::1]:9081: connect: connection refused 
[31mERRO[0m[2021/12/02 17:06:32] [textsecure-crayfish-ws] Failed to start listening  [31merror[0m="dial tcp [::1]:9081: connect: connection refused"
[37mDEBU[0m[2021/12/02 17:06:34] [textsecure-crayfish-ws] websocket connecting to crayfish-server 
[31mERRO[0m[2021/12/02 17:06:34] dial tcp [::1]:9081: connect: connection refused 
[31mERRO[0m[2021/12/02 17:06:34] [textsecure-crayfish-ws] Failed to start listening  [31merror[0m="dial tcp [::1]:9081: connect: connection refused"
[36mINFO[0m[2021/12/02 17:06:36] [axolotl-qml] QObject::killTimer: Timers cannot be stopped from another thread
QObject::startTimer: Timers cannot be started from another thread 
[37mDEBU[0m[2021/12/02 17:06:36] [textsecure-crayfish-ws] websocket connecting to crayfish-server 
[31mERRO[0m[2021/12/02 17:06:36] dial tcp [::1]:9081: connect: connection refused 
[31mERRO[0m[2021/12/02 17:06:36] [textsecure-crayfish-ws] Failed to start listening  [31merror[0m="dial tcp [::1]:9081: connect: connection refused"`

**Comment by phiibuntu** [comment]
Hi I have very same probleme. It seems that If I have not the axolotl client open on my ubuntu (PC) session, my axolotl client in my phone doesn't receive messages.  I can write to my contacts they receive my messages. But I don't receive answer.
I hope it helps. 
(I answer for no importing contact, you muste recevie a first message then add the contact, then you ll can import contact from contact app).

**Comment by nanu-c** [comment]
That's a difficult one for me, can you tell me what the output of the following commands is?
```
ps fx | grep crayfish
sudo netstat -tulpen | grep crayfish
```

**Comment by flaun** [comment]
This are new logfiles after deleting again everything including the registration. Then I downloaded the open-store version, registered again and immediately updated axolotl to the new version from telegram (03.12.2022).
Still not possible to add contacts or receive messages.

[application-click-textsecure.nanuc_textsecure_1.0.8.log](https://github.com/nanu-c/axolotl/files/7806776/application-click-textsecure.nanuc_textsecure_1.0.8.log)

**Comment by Flaburgan** [comment]
Hi @phiibuntu and thank you for using Axolotl. You wrote "*It seems that If I have not the axolotl client open on my ubuntu (PC) session, my axolotl client in my phone doesn't receive messages.*" Do you have 2 installations of Axolotl with the same phone number at the same time? This isn't supported, Axolotl is a primary Signal client, you can have only one installation of it. You also can't have the official Signal installed on a phone at the same time.

**Comment by flaun** [comment]
nanu-c found the reason. Thanks so much.

[https://github.com/signal-golang/textsecure/pull/55/files](url)
