### ISSUE TITLE
Messages to groups aren't sent

### ISSUE THREAD

**Issue by Flaburgan** [nanu-c/axolotl#66]
### Description

When writing a message to a group, it is never received by other contacts.

### Steps to Reproduce

1. Join a group
2. Write a message

**Expected behavior:**
The message should be sent, the time at bottom of it should be "Now", there should be two checks at the bottom of the message

**Actual behavior:**

There is only one check at the bottom of the message, the time is "A long while ago" and the message is never received

**Reproduces how often:**

Each time.

#### Versions

0.4.1

#### Device
Fairphone 2 OTA-9 stable

#### Link to Debug Log
Please provide the link generated by `Settings->Advanced-> Submit Debug Log`

There is no "Submit" in the debug option in settings. I have activated them and have a shell on my phone but no idea where to find them

**Comment by nanu-c** [comment]
Ask someone to update the group. This happens on my side, when my key changed but the group is not updated

**Comment by Flaburgan** [comment]
I did that. Before I did that, I wasn't even able to receive group messages. Now I can, but I can't answer.

**Comment by yo-k** [comment]
@Flaburgan try out current version 0.7.0 . Should be fixed. Please close this ticket if successful.

**Comment by yo-k** [comment]
I think it is fixed in 0.7.0 so I close this ticket. If not, reopen this ticket, please. Thank you for your bug report.

**Comment by Flaburgan** [comment]
Hi! So, as said in another thread some time ago, I removed this app (v0.4.3) and installed the "real" Signal apk using anbox. That's why I wasn't able to tell if I still reproduce. But last week, a message in Signal told me my version was outdated and I needed to upgrade or I won't be able to send messages to my contact anymore. Trying to update the apk in Anbox, I removed it and my keys. So now that my keys are gone, I can try this app again! So I'm back in the game. I already have some strange behaviors, maybe we can chat about it in #ubports in IRC?

**Comment by Flaburgan** [comment]
Hi, I'm sorry but I still have the problem in 0.7. 

- I receive the messages from the group, but its name is an hexadecimal string, and I have the yellow message asking for the group to be updated.
- I asked my friend to leave the group
- Another friend added him back in the group
- The yellow message disappeared and the text field is here (the name is still hexa).
- When I post a message, the date of the message is the 1st of January (no year, but I guess 1970?)
- The other member of the group don't receive the message
- If I go to the conversations list and then back to the group, the message isn't there anymore.

Could you please re-open that issue?

**Comment by nanu-c** [comment]
Please try to readd your useraccount, not someone else if that's possible?

**Comment by Flaburgan** [comment]
But others can't kick me out, I should leave, but I see no way to do it the only item in the menu is "Mute".

**Comment by Flaburgan** [comment]
FTR, I just had the "sent from the past" bug with the message never sent and then disappearing in conversations with a single contact too. So it's maybe not linked to group.

**Comment by Flaburgan** [comment]
This issue never was about leaving group, so I renamed it back to the original problem. However, I'll close it as the situation greatly improved, even if I still have some problems, it can be as generic as this issue, so closing.

I opened https://github.com/nanu-c/axolotl/issues/182 about the capability of leaving groups.
