### ISSUE TITLE
question : Is  PC client is needed to update smartphone axolotl client?

### ISSUE THREAD

**Issue by phiibuntu** [nanu-c/axolotl#693]
**Is your feature request related to a problem? Please describe.**

Problem : Is the UT client need a PC client connected to be update and synchronise?

**Describe the solution you'd like**
If yes feature need is : Smartphone client synchronise alone (no other client connected needed.

**Describe alternatives you've considered**

**Additional context**

**Comment by nanu-c** [comment]
I don't know if i understand your question. Actually Axolotl could work as is without any other device, but it works better if you use Signal-Desktop for some features like calls etc.

**Comment by Flaburgan** [comment]
Hello @phiibuntu and thank you for your interest about Axolotl.
No, Axolotl doesn't need any external PC client to be updated, as you're using Ubuntu Touch, simply update it from the OpenStore when a new version is available. Teasing: a new one should be available really soon ;)
