### ISSUE TITLE
[BUG] No cross to close a picture

### ISSUE THREAD

**Issue by nalysius** [nanu-c/axolotl#720]
### Description

When clicking on an attachment to see it in almost fullscreen there are two buttons on top - right of the screen, one to download it and the other one to close the view.  
The closing button has no cross (X) it's just a white empty button.

### Steps to Reproduce

1. Receive an image
2. Click on the image to view it

**Expected behavior:** The button should have a X inside.

**Actual behavior:** The button is empty

#### Versions

1.0.9

#### Device

FP3 - UT - OTA 21

**Comment by nuehm-arno** [comment]
Works fine. Closing.
