### ISSUE TITLE
[BUG] Error connecting to internal crayfish server on new install

### ISSUE THREAD

**Issue by rja-aus** [nanu-c/axolotl#764]
### Description

I have just installed a new axolotl on a new Pinephone Pro running Mobian, based on the nuehm-arno .deb install file.

### Steps to Reproduce

1. Install axolotl using nuehm-arno's .deb file on a Pinephone pro running Mobian
2. run axolotl from terminal

**Expected behavior:** Axolotl works normally

**Actual behavior:** 
- Error messages  in this order:
- DEBU [textsecure-crayfish-ws] BackendStartListening 
- DEBU [textsecure-crayfish-ws] websocket connecting to crayfish-server
- ERRO [textsecure-crayfish-ws] dial tcp [::1]:9081: connect: connection refused
- ERRO [textsecure-crayfish-ws] Failed to start listening error = "dial tcp [::1]:9081 connect: connection refused"
- then a bunch of INFO messages saying starting libsignal-service web socket at ws://127.0.0.1:9081/libsignal

Additionally, the Axolotl app opens up, but it is stuck sitting on either the spinning circle or sometimes the Axolotl welcome screen (pressing 'Next' does nothing)

#### Versions

1.1.0-1

#### Device
Pinephone Pro Explorer running Mobian bookworm

#### Link to Debug Log
https://pastebin.com/Z6GkPTp8

**Comment by jonsger** [comment]
I see this issue as well on Librem 5/PureOS 10.

**Comment by jonsger** [comment]
> Is this still a bug? Or is it solved with v1.5.0?

I got Axolotl working in the mean time. I'm currently at 1.5.1. This specific issue is gone for me. Can't tell when excactly...
