### ISSUE TITLE
[BUG] unable to import contacts

### ISSUE THREAD

**Issue by Eike17** [nanu-c/axolotl#768]
### Description

I am unalbe to import my Contacts in Axolotl. I tried to select one or two contacts from my contacts at the phone. I also tried to import a .vcf-File. Axolotl shows the message "Kontakte werden importiert, komm später zurück" ("importing contacts, come back later). 

### Steps to Reproduce

1. Open Axolotl
2. Navigate to "contacts"
3. Select "Import Contacts"
4. Either select contacts-App or Filemanager
5. Select Contacts in contacts-App or select .vcf File in Filemanager
6. Message "Kontakte werden importiert, komm später zurück" ("importing contacts, come back later). 

**Expected behavior:** See and use my contacts 

**Actual behavior:** No contacts in Axolotl

#### Versions

Axolotl Beta 1.1.0

#### Device
Volla Phone with Ubuntu (OTA-22)

#### Link to Debug Log
[application-click-textsecure.nanuc_textsecure_1.1.0.log](https://github.com/nanu-c/axolotl/files/8161595/application-click-textsecure.nanuc_textsecure_1.1.0.log)

**Comment by MoemUT** [comment]
I had this same problem, and it was easy to solve. It turned out a file named contacts.yml was corrupted in a very specific way: for one contact, there was a name listed where a telephone number should have been. I deleted that contact, saved the file, and from then on it was possible for me to import and add contacts again.
So give it a try.

**Comment by Eike17** [comment]
Thanks @MoemUT ! I cleaned my contacts.yml, now I have a few contacts imported. I had about 400+ Contacts. I reduced it to nearly 10, my "signal"-contacts. So i still don't know which contact entry was the problem. It would be helpful to know which contact is corrupt.

**Comment by MoemUT** [comment]
Do you have a backup of the file? If you do, check it to see whether there is any contact that has anything in the "tel:" field that os not clearly a telephone number, or is formatted wrong (spaces? hyphens? the wrong number of digits?)

Keep in mind that the contacts need to be on Signal or you can't (shouldn't) add them in Axolotl.

Also I don't think the contact was already inherently corrupt in my Contacts app. I believe that the corruption happened during an attempt to add them to Axolotl.

**Comment by S1C1C1** [comment]
I am seeing the same issue. I cannot import any contacts on my  phone - ubports pixel 3a

**Comment by digbyf** [comment]
On a one plus one, unable to import contacts.. solution for me was export contacts to vcf file then import via file manager..

**Comment by nanu-c** [comment]
see  #897
