### ISSUE TITLE
Scan QR-Code for linking desktop directly on ut and focus on click

### ISSUE THREAD

**Issue by fredldotme** [nanu-c/axolotl#79]
**Is your feature request related to a problem? Please describe.**
Scanning the QR code to connect the Signal Desktop application with the devices is hard/impossible when the camera is unfocused.

**Describe the solution you'd like**
Either auto-focus every few seconds or a tap-to-focus would help in this case.

**Comment by nanu-c** [comment]
This is solved in 0.8.3
