### ISSUE TITLE
[BUG] Unable to input verification code on registration

### ISSUE THREAD

**Issue by kpenfound** [nanu-c/axolotl#798]
### Description

When registering the device, after you pass the captcha and get to the verification code entry form, you're unable to input anything into the boxes

### Steps to Reproduce

1. Unregister device if its already registered
2. Attempt to register
3. Enter phone number
4. Pass captcha
5. Get stuck at verification entry

**Expected behavior:** [What you expect to happen]
Enter verification code successfully

**Actual behavior:** [What actually happens]
Unable to enter

#### Versions

v1.2.0, installed via deb

#### Device
Pinephone / mobian

#### Link to Debug Log
Please provide a link to debug from ~/.cache/upstart/application-click-textsecure.nanuc_textsecure*.log
Be careful it contains sensible data

No log file there.

Some additional info:
I've tried replacing the `VerifcationPinInput` component with just a text input, as in replacing
https://github.com/nanu-c/axolotl/blob/main/axolotl-web/src/pages/Verification.vue#L16
with
`<input v-model="code" type="text">`
and still can't input anything. So there must be something going on at a higher level than the component, which rules that out probably.

Still investigating on my end.

**Comment by kpenfound** [comment]
Confirmed, after seeing a related telegram post, that I'm able to enter the code in firefox, just not electron

**Comment by langfingaz** [comment]
I have the same problem. Installed Axolotl v1.2.0 via flatpak on Arch Linux Arm (DanctNIX).

Entering does neither work with a physical keyboard.

Thanks @kpenfound for the tip to complete the registration via http://127.0.0.1:9080. I had to select each of the 6 fields there individually as the cursor did not jump one further after entering one digit - but that's another issue. I've got it working now :+1:

**Comment by kpenfound** [comment]
Thanks @nuehm-arno , that looks like https://github.com/signal-golang/textsecure/issues/57
I'll spend some time trying to dig in

**Comment by kpenfound** [comment]
That error message appears to be unrelated unfortunately, but I opened up a PR for it.
This issue seems to be caused by something happening during the captcha step. Maybe from overriding the window.onload. Still testing. I messed with the routing to skip the captcha and the input works normally, so the Verification component itself is fine.

**Comment by nanu-c** [comment]
Maybe it's the onload alert that shouldn't be there.

**Comment by kpenfound** [comment]
Yeah good call @nanu-c , that looks like it did it
