### ISSUE TITLE
[Feature] Close Stale Issues and PRs

### ISSUE THREAD

**Issue by olof-nord** [nanu-c/axolotl#806]
**Is your feature request related to a problem? Please describe.**
Many old issues remain for years without a clear path forward, or with open questions.

**Describe the solution you'd like**
Give the project a better chance to prioritize and allow focus on what is the most important issues.

**Describe alternatives you've considered**
Continue as we work now and not auto-close anything. Perhaps simply clarify some kind of priorization and/or roadmap?

**Additional context**
Example: https://github.com/nanu-c/axolotl/issues/53 which today is ca four years old.

A quick search shows some GitHub Actions, for example "close-stale-issues" and "probot/stale".

**Comment by nanu-c** [comment]
That would be cool, if it could work automatically :)

**Comment by olof-nord** [comment]
With the above linked MR merged, I will close this issue as completed.
