### ISSUE TITLE
[BUG] cant create contact

### ISSUE THREAD

**Issue by toraschi** [nanu-c/axolotl#808]
Can not create contacts 
When I want to add a contact manually in the app it's not saved to the contactlist

### Steps to Reproduce

1. [add new contact]
2. [fill the feld contactname]
3. [type or paste a phone number]
4. [press safe button]

**Expected behavior:** [a new contact to be created in the contact list]

**Actual behavior:** [nothing the list remains empty]

#### 1.2

Please provide the Version as written in `Settings->About Axolotl`

#### Device Pixel 3a
Ubuntu touch OTA 22

#### Link t
Please provide a link to debug from ~/.cache/upstart/application-click-
![screenshot20220427_145433294](https://user-images.githubusercontent.com/32172610/165526343-16a7d802-b86f-4fbd-bb9a-ff38b8d239f6.png)
Cant copy the log from UT Logviwer

**Comment by dorje42** [comment]
Same here.

Version: 1.4.0
OnePlusOne
Ubuntu touch OTA-23

**Comment by nanu-c** [comment]
discussion continues here #897
