### ISSUE TITLE
Warn people that an Axolotl registration will break a current phone-desktop registration!

### ISSUE THREAD

**Issue by firefoxlover** [nanu-c/axolotl#811]
Only a small thing, but due to Signals strict phone-desktop pairing mechanism, when registering Axolotl, both phone and regular Desktop wont work anymore.

Also, you cant use Axolotl on Desktop together with Signal mobile.

After deleting the Axolotl registration I had to wait a while to be able to register on Signal again, I didnt loose any backups and my codes didnt change.

Nonetheless a warning should be displayed at the beginning, that users wanting to use regular mobile (iOS, Android) and Desktop (Windows, macOS, Flatpak or Snap), they should use a second phone number for testing.

Thanks for this great app! An important step towards convergence.

**Comment by zenhack** [comment]
Thanks for the warning :)

Do we know what the problem is here, and how hard it would be to fix?

Also, is this only a problem with registration through axolotl, or is it not possible to link an axolotl install as a device with existing signal clients?

**Comment by firefoxlover** [comment]
The problem is the strict "only one phone" policy of signal. Axolotl imitates a phone, because of that it breaks the current install.
