### ISSUE TITLE
create public key QR-Code that could be scanned

### ISSUE THREAD

**Issue by yo-k** [nanu-c/axolotl#82]
**Is your feature request related to a problem? Please describe.**
Android signal users got the message that my key has changed, because I re-registered to signal. I could not find any QR-Code with the updated public key for scanning.

**Describe the solution you'd like**
A menu point "generate QR-Code" with possibility to show and/or export public key/QR-code

**Describe alternatives you've considered**
show/export public key without QR-Code

**Comment**
I think it is a very important feature.

**Links**
Maybe it is associated to #79

**Comment by nanu-c** [comment]
you can show the binary code as in https://github.com/nanu-c/textsecure-qml/commit/1f985e07ea9a2e079d48f3b54025dbd350539d5a implemented. Transmitting an image from the backend to the gui isn't implemented yet/ a bigger task

**Comment by yo-k** [comment]
Thanks for you answer and I will be patient :-)

I don't understand your hint

> you can show the binary code as in [1f985e0](https://github.com/nanu-c/textsecure-qml/commit/1f985e07ea9a2e079d48f3b54025dbd350539d5a) implemented. 

What should I do with that diff code?
I there a cli export function to generate a QR-Code on another machine?

**Comment by nanu-c** [comment]
You can either wait for the next release or build that commit, then it looks like that:
![grafik](https://user-images.githubusercontent.com/404058/66733317-70021800-ee5f-11e9-8385-352fd0e5de58.png)

**Comment by yo-k** [comment]
cool, got it. Thanks a lot.

**Comment by nanu-c** [comment]
This is solved in 0.8.3
