### ISSUE TITLE
[BUG] Flathub page screenshot has kind of irritating contents

### ISSUE THREAD

**Issue by ell1e** [nanu-c/axolotl#833]
### Description

The axolotl flathub page screenshot has kind of irritating contents when you read the actual text. Is this meant to be a joke? Some political point? It just seems very misplaced. Like, I don't even mind if OSS gets political for the right reasons, but if there is a message to this then it should be clearer maybe - or otherwise, maybe stay out of the topic. Especially with the US having a sort of not so good chain of news on this lately, it's just not a good association and I don't get why you'd put it into a screenshot.

### Steps to Reproduce

1. Go to https://flathub.org/apps/details/org.nanuc.Axolotl
2. Read text in example messages in screenshots

**Expected behavior:** neutral

**Actual behavior:** reference to emotional topic that seems misplaced and random

#### Versions

affects store page

#### Device
affects store page

#### Link to Debug Log
affects store page

**Comment by olof-nord** [comment]
Hello @ell1e!

The exchange in the screenshot is a reference to a song from Bob Dylan, Hurricane. Its released in 1976, however as most of his songs are, its very much relevant still today as I can see from this issue.

The song is, quoting Wikipedia, "was one of his [Bob Dylan] few "protest songs" during the 1970s".
https://en.wikipedia.org/wiki/Hurricane_(Bob_Dylan_song)

During the axolotl initial startup further references to other songs made by Dylan can be found too.

**Comment by olof-nord** [comment]
The screenshot can be found in the [repo](https://github.com/nanu-c/axolotl/blob/main/screenshot.png) - if you have a suggestion for a better content which fits better feel free to submit a MR. There was some discussion in the axolotl-dev Telegram group about it, it seems more than you thought another screenshot would be more fitting.

**Comment by olof-nord** [comment]
@nanu-c did change the screenshot with PR #867, I guess we can close this issue now?

**Comment by nuehm-arno** [comment]
It is not yet changed on Flathub...
