### ISSUE TITLE
[BUG] SIGSEGV in Flatpak 1.2.0

### ISSUE THREAD

**Issue by kop316** [nanu-c/axolotl#835]
### Description

In trying to run the flatpak, I am getting a SIGSEGV or an error.. This is on A Librem5/PureOS (Based on Debian Bullseye)

### Steps to Reproduce

1. `sudo flatpak install flathub org.nanuc.Axolotl`
2. `flatpak run org.nanuc.Axolotl`

I will either get: 
```
purism@pureos:~$ flatpak run org.nanuc.Axolotl
time="2022-06-22T09:21:32-04:00" level=info msg="[axolotl] Starting axolotl version 1.2.0"
time="2022-06-22T09:21:32-04:00" level=info msg="[axolotl] Setup completed"
time="2022-06-22T09:21:32-04:00" level=info msg="[axolotl-electron] starting astilelectron with the following switches: [--disable-dev-shm-usage --no-sandbox --ozone-platform-hint=auto]"
time="2022-06-22T09:21:32-04:00" level=info msg="astikit: starting worker..."
time="2022-06-22T09:21:32-04:00" level=info msg="[axolotl] Axolotl server started"
time="2022-06-22T09:21:32-04:00" level=info msg="[axolotl] Starting axolotl ws"
time="2022-06-22T09:21:32-04:00" level=info msg="[axolotl] Loading Chats"
time="2022-06-22T09:21:32-04:00" level=info msg="[axolotl] Db setup finished"
time="2022/06/22 09:21:32" level=info msg="[textsecure-crayfish] Starting crayfish-backend"
time="2022/06/22 09:21:32" level=info msg="[crayfish] starting crayfish 7bbaf1665234ce8dd3455ded2164b107fae7f972\n"
time="2022/06/22 09:21:32" level=info msg="[crayfish] Starting libsignal-service web socket at ws://127.0.0.1:9081/libsignal\n"
time="2022/06/22 09:21:33" level=info msg="[crayfish] establishing client connection... WebSocket\n"
```

Followed by:
![photo_2022-06-22_09-23-09](https://user-images.githubusercontent.com/16343055/175039809-a72116c5-6aba-4eb6-982b-941b8516b18d.jpg)

Or:
```
time="2022-06-22T09:16:38-04:00" level=info msg="[axolotl] Starting axolotl version 1.2.0"
time="2022-06-22T09:16:38-04:00" level=info msg="[axolotl] Setup completed"
time="2022-06-22T09:16:38-04:00" level=info msg="[axolotl-electron] starting astilelectron with the following switches: [--disable-dev-shm-usage --no-sandbox --ozone-platform-hint=auto]"
time="2022-06-22T09:16:38-04:00" level=info msg="astikit: starting worker..."
time="2022-06-22T09:16:38-04:00" level=info msg="[axolotl] Axolotl server started"
time="2022-06-22T09:16:38-04:00" level=info msg="[axolotl] Starting axolotl ws"
time="2022-06-22T09:16:38-04:00" level=error msg="[axolotl] webserver errorlisten tcp 127.0.0.1:9080: bind: address already in use"
time="2022-06-22T09:16:38-04:00" level=error msg="[axolotl] webserver error"
time="2022-06-22T09:16:38-04:00" level=error msg="[axolotl] webserver error"
time="2022-06-22T09:16:38-04:00" level=info msg="[axolotl] ending axolotl"
panic: http: multiple registrations for /
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8bb834]

goroutine 20 [running]:
github.com/signal-golang/textsecure/crayfish.(*CrayfishInstance).Stop(0x0)
        /run/build/axolotl-electron-bundle/src/github.com/signal-golang/textsecure/crayfish/backend.go:536 +0x24
main.endAxolotlGracefully()
        /run/build/axolotl-electron-bundle/src/github.com/nanu-c/axolotl/main.go:57 +0x68
panic({0xaf95a0, 0x40000321d0})
        /usr/lib/sdk/golang/src/runtime/panic.go:838 +0x20c
net/http.(*ServeMux).Handle(0x7a2d980, {0xd9ee1c, 0x1}, {0xda5028?, 0x40000321c0})
        /usr/lib/sdk/golang/src/net/http/server.go:2478 +0x20c
net/http.Handle(...)
        /usr/lib/sdk/golang/src/net/http/server.go:2521
github.com/nanu-c/axolotl/app/webserver.webserver()
        /run/build/axolotl-electron-bundle/src/github.com/nanu-c/axolotl/app/webserver/webserver.go:463 +0x22c
github.com/nanu-c/axolotl/app/webserver.Run()
        /run/build/axolotl-electron-bundle/src/github.com/nanu-c/axolotl/app/webserver/webserver.go:43 +0x6c
main.runWebserver()
        /run/build/axolotl-electron-bundle/src/github.com/nanu-c/axolotl/main.go:214 +0x68
created by main.main
        /run/build/axolotl-electron-bundle/src/github.com/nanu-c/axolotl/main.go:225 +0x94
```

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Versions
Flatpak 1.2.0

#### Device
Librem 5, PureOS (Based on Debian Bullseye)

#### Link to Debug Log
This file does not exist

**Comment by olof-nord** [comment]
Looking at the error message, it seems something similar to what is described here: https://github.com/asticode/astilectron/issues/40

I dont exactly know when the issue was fixed, but upgrading to the latest astilectron bundler seems to be a good first step.
Thats done in PR https://github.com/nanu-c/axolotl/pull/836.

**Comment by kop316** [comment]
> Looking at the error message, it seems something similar to what is described here: [asticode/astilectron#40](https://github.com/asticode/astilectron/issues/40)
> 
> I dont exactly know when the issue was fixed, but upgrading to the latest astilectron bundler seems to be a good first step. Thats done in PR #836.

Gotcha. Looking closer, it seems like 1.3.0 has been released, so I suppose that will be upgraded when the flatpak is upgraded to on flathub?

**Comment by olof-nord** [comment]
Well, the PR linked will not specifically be part of 1.3.0, but in a 1.3.1 release or something - the git tag is set already.
Im working on the flathub release for 1.3.0 though - that will include all the improvements listed in [1.3.0](https://github.com/nanu-c/axolotl/releases/tag/v1.3.0)

**Comment by kop316** [comment]
This seems to be fixed in 1.3.1 (deb), So I am closing

**Comment by kkofler** [comment]
> This seems to be fixed in 1.3.1 (deb)

It is "fixed" because you switched from using a Flatpak to using a deb. This is still broken in the Flatpak. See flathub/org.nanuc.Axolotl#9.

**Comment by kkofler** [comment]
Though actually, the segfault you are getting is not the same as the one I am getting.

**Comment by kop316** [comment]
> Though actually, the segfault you are getting is not the same as the one I am getting.

If that is the case, I think this specific issue is still fixed, and the issue you are having should stay a different issue.
