### ISSUE TITLE
[BUG] Missing binaries for release v1.3.0

### ISSUE THREAD

**Issue by raphj** [nanu-c/axolotl#840]
### Description

From the README, it seems we should find the Debian packages in the releases. I don't find it for the [v1.3.0 release](https://github.com/nanu-c/axolotl/releases/tag/v1.3.0).

Here's a report In case I did not miss something and you didn't notice :-)

Thanks for your work.

**Comment by kkofler** [comment]
In fact, all binaries are missing, also Flatpak etc.

**Comment by nanu-c** [comment]
Fixed with https://github.com/nanu-c/axolotl/releases/tag/v1.3.1

**Comment by raphj** [comment]
Thanks @nanu-c :-)

**Comment by raphj** [comment]
Hello :-)

Head's up, the deb packages are missing again for the last version (v1.5.1).
If there is anything I can do to help, let me know

**Comment by nuehm-arno** [comment]
I think, that was intentional, since there are no binaries at all in the assets section. This was mainly a flatpak fix release (correct me, if I'm wrong, @nanu-c).
