### ISSUE TITLE
[Feature] Remain Running in the Background

### ISSUE THREAD

**Issue by qstambaugh** [nanu-c/axolotl#850]
**Is your feature request related to a problem? Please describe.**
I'm currently using Axolotl (flatpak) on my Pinephone running Mobian. I have to leave Axolotl open to receive messages.

**Describe the solution you'd like**
An option to have it background when closing the window.

**Additional context**
Example: Dino has an option to stay in the background with the "--gapplication-service" flag.

**Comment by nanu-c** [comment]
We have this already with `-e server` please look into the readme -> https://github.com/nanu-c/axolotl#run-flags
