### ISSUE TITLE
[BUG] "Enter your registration pin" doesn't work on Librem L5 Phone

### ISSUE THREAD

**Issue by RalphRGitHub** [nanu-c/axolotl#862]
### Description
The "Enter your registration pin" page does not accept keyboard input from either the keyboard emulators in the Librem L5
or from a physically connected USB-C keyboard
[Description of the issue]
The "Enter your registration pin" page does not accept keyboard input from either the keyboard emulators in the Librem L5
or from a physically connected USB-C keyboard
### Steps to Reproduce

1. [First Step] install the app on the Librem L5 from: https://flathub.org/apps/details/org.nanuc.Axolotl
3. [Second Step] run Axolotl, and start typing the required user data on the following pages, 
4. On the opening page: welcome screen click the "Next" button
5. On the 2nd page: Connect with Signal, type your cell number and click the "request code" button
6. On the 3rd page: click on the "overriding onload" button first then click on the "I'm not a robot" box click on the appropiate boxes
7. Wait to receive the code from the SMS text app
8. Try typing the code you recived from the SMS text app into the  "Enter your registration pin" page, but you can't

**Expected behavior:** [What you expect to happen]
I should be able to type the code I received via SMS text

**Actual behavior:** [What actually happens]
The page initial setup page "Enter your registration pin" does not accept input from any virtual keyboard or a physical keyboard
#### Versions
Axolotl 1.2.0
Please provide the Version as written in `Settings->About Axolotl`
I can't get to that page as the install is not completed
#### Device
What device or OS are you using?
Im using a Librem L5 phone with their latest Pure OS, OS Type 64-bit, GNOME version 3.38.5, Window System Wayland
#### Link to Debug Log
Please provide a link to debug from ~/.cache/upstart/application-click-textsecure.nanuc_textsecure*.log
there's no ~/.cache/upstart in my file system, I think is becuase the App never finished configuring correctly
Be careful it contains sensible data

**Comment by kylerankin** [comment]
I've noticed two different instances where I have had difficulty with keyboard input in Axolotl on my Librem 5:

1. when multiple QT-based applications are open at the same time, the last-opened one seems to have precedence. Closing and then re-opening axolotl seems to give it the keyboard input in that instance.
2. When automatically running at startup. In that case restarting axolotl also seems to remedy it.

**Comment by RalphRGitHub** [comment]
Hey, thanks for the feed back,
1. when I tried entering the code, no other QT application was open, other than the SMS text app which I need to receive the code
and after receiving the code I closed the SMS app, so the only app focus is axolotl
 2. I don't have axolotl set up to auto-start

what I find curious is that the input the cell number page just before the enter the code page receives keyboard input with no problem.

**Comment by nanu-c** [comment]
Please try the version from here https://github.com/nanu-c/axolotl/releases/tag/v1.3.1

**Comment by RalphRGitHub** [comment]
> Please try the version from here https://github.com/nanu-c/axolotl/releases/tag/v1.3.1

Will do, Thanks

**Comment by RalphRGitHub** [comment]
> > Please try the version from here https://github.com/nanu-c/axolotl/releases/tag/v1.3.1
> 
> Will do, Thanks

yes version v1.3.1 fixes that issue,
Thanks!

**Comment by phs** [comment]
This issue affects me as well, though I am on a pinephone.

I'd like to try the v1.3.1 you mention, but the linked flatpak files (I'm guessing it should be [this one][0]) appear to be x86_64 rather than aarch64?  Or maybe I'm doing it wrong, I'm new to flatpak.

How should we try v1.3.1 on our mobile arm devices?

[0]: https://github.com/nanu-c/axolotl/releases/download/v1.3.1/axolotl-web.flatpak
