### ISSUE TITLE
[BUG] AppImage complains about misssing shared library

### ISSUE THREAD

**Issue by kop316** [nanu-c/axolotl#865]
### Description

[Description of the issue]

Hello! For version 1.3.1, The AppImage cannot find a shared library. IIRC, AppImages should be entirely self-contained and not need a shared library:

```
chris@SpaceballsTheX2100:~/Downloads$ chmod +x Axolotl-x86_64.AppImage 
chris@SpaceballsTheX2100:~/Downloads$ ./Axolotl-x86_64.AppImage 
usr/bin/axolotl: error while loading shared libraries: libzkgroup_linux_x86_64.so: cannot open shared object file: No such file or directory
```

This was found on Debian Bookworm

**Comment by nanu-c** [comment]
There is something wrong in the appimage packaging. For now you can find the file here: https://github.com/nanu-c/zkgroup/tree/main/lib

**Comment by nanu-c** [comment]
#985 will solve this.
