### ISSUE TITLE
[BUG] Axolotl won't start on Fedora

### ISSUE THREAD

**Issue by carlmo** [nanu-c/axolotl#873]
### Description

[Description of the issue]

### Steps to Reproduce

1. Install Fedora on pinephone
2. [root@fedora ~]# flatpak install flathub Axolotl
3. [pine@fedora ~]$ flatpak run org.nanuc.Axolotl

**Expected behavior:** [What you expect to happen]
Axolotl should start
**Actual behavior:** [What actually happens]
Axolotl does not start
#### Versions

Please provide the Version as written in `Settings->About Axolotl`

#### Device
Pinephone Fedora using latest version

https://github.com/nikhiljha/pp-fedora-sdsetup/releases/tag/v0.7.0

#### Link to Debug Log
[pine@fedora ~]$ flatpak run org.nanuc.Axolotl
F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Remote peer disconnected
time="2022-08-23T15:43:51-04:00" level=info msg="[axolotl] Starting axolotl version 1.2.0"
time="2022-08-23T15:43:51-04:00" level=info msg="[axolotl] Setup completed"
time="2022-08-23T15:43:51-04:00" level=info msg="[axolotl] Axolotl server started"
time="2022-08-23T15:43:51-04:00" level=info msg="[axolotl] Starting axolotl ws"
time="2022-08-23T15:43:51-04:00" level=info msg="[axolotl-electron] starting astilelectron with the following switches: [--disable-dev-shm-usage --no-sandbox --ozone-platform-hint=auto]"
time="2022-08-23T15:43:51-04:00" level=info msg="astikit: starting worker..."
time="2022-08-23T15:43:51-04:00" level=info msg="[axolotl] Loading Chats"
time="2022-08-23T15:43:51-04:00" level=info msg="[axolotl] Db setup finished"
time="2022/08/23 15:43:51" level=info msg="[textsecure-crayfish] Starting crayfish-backend"
time="2022/08/23 15:43:51" level=info msg="[crayfish] starting crayfish 7bbaf1665234ce8dd3455ded2164b107fae7f972\n"
time="2022/08/23 15:43:51" level=info msg="[crayfish] Starting libsignal-service web socket at ws://127.0.0.1:9081/libsignal\n"
time="2022/08/23 15:43:52" level=info msg="[crayfish] establishing client connection... WebSocket\n"
time="2022-08-23T15:43:52-04:00" level=error msg="'/home/pine/.var/app/org.nanuc.Axolotl/data/vendor/electron-linux-arm64/electron' exited with code: 1"
time="2022-08-23T15:43:52-04:00" level=info msg="astikit: stopping worker..."
time="2022/08/23 15:43:52" level=error msg="[axolotl-electron] main: creating window failed: context canceled"
time="2022-08-23T15:43:52-04:00" level=info msg="astikit: worker is now waiting..."
time="2022/08/23 15:43:52" level=info msg="[axolotl] ending axolotl"
time="2022-08-23T15:43:52-04:00" level=error msg="accept tcp 127.0.0.1:39475: use of closed network connection while TCP accepting"

**Comment by baduhai** [comment]
I'm getting the same issue on NixOS.

**Comment by olof-nord** [comment]
I believe this issue is related to https://github.com/nanu-c/axolotl/issues/433 and to https://github.com/flathub/org.nanuc.Axolotl/issues/9. From what I can tell the problem is "creating window failed: context canceled" + "use of closed network connection while TCP accepting" across all of them.

**Comment by nanu-c** [comment]
#985 will switch from electron to tauri
