### ISSUE TITLE
we are still using hex codes instead of safety numbers

### ISSUE THREAD

**Issue by yo-k** [nanu-c/axolotl#88]
### Description
Since 2016 signal app from signal.org has switched from hex code to safety numbers. That means, ios or android users see safety numbers (on the right). They do not know what to do with hex code (on the left)
![grafik](https://signal.org/blog/images/verify-before-after.png)

**Expected behavior:**
The image on the right shows QR-Code and safety numbers. QR-Code is handled in another feature request #82 . Anyhow, we should use/show safety numbers instead of hex code. Read this signal blog https://signal.org/blog/safety-number-updates/
 
**Actual behavior:**
showing hex coded fingerprint
> ![grafik](https://user-images.githubusercontent.com/404058/66733317-70021800-ee5f-11e9-8385-352fd0e5de58.png)

#### Versions

axolotl beta 0.7.0 and some releases earlier. 

#### Device
bq e4.5 ota10

#### Links
https://signal.org/blog/safety-number-updates/

**Comment by nanu-c** [comment]
Somehow difficult, because they don't describe how the numbers are calculated so I/we have to dig in the java code of the original signal app

**Comment by yo-k** [comment]
Yes, I did not find it either. But you also think that should be switched to safety numbers?

**Comment by yo-k** [comment]
maybe one puzzle part
https://github.com/signalapp/Signal-Desktop/blob/development/components/qrcode/qrcode.js

**Comment by Blackoverflow** [comment]
Another puzzle part: https://github.com/signalapp/libsignal-protocol-java/blob/master/java/src/main/java/org/whispersystems/libsignal/fingerprint/NumericFingerprintGenerator.java

**Comment by yo-k** [comment]
well, I think the task is to present the already existing public key as a QR code. However, not as a hex combination but as a security number.  Maybe I'm wrong.

**Comment by Flaburgan** [comment]
I confirm I would like a way to check keys with my contacts using the signal apk.

**Comment by nanu-c** [comment]
So hey, lets find the calculation of these numbers in the signal android source, I need an investigator, that finds the formular. Then implementation is more than easy...

**Comment by nanu-c** [comment]
> Another puzzle part: https://github.com/signalapp/libsignal-protocol-java/blob/master/java/src/main/java/org/whispersystems/libsignal/fingerprint/NumericFingerprintGenerator.java
> 
> This is used in [VerifyIdentityActivity.java, Line 283](https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/VerifyIdentityActivity.java#L283) with 5200 iterations.

Thanks a lot for that!

**Comment by nanu-c** [comment]
I tried my best yesterday, but the generated number is wrong. Maybe someone can help me :) Here are my findings. At least I dont know much about bit shifting. 
https://gist.github.com/nanu-c/f885b928b9e43a7167258dd70dc186d6

**Comment by Flaburgan** [comment]
Would it be useful if I give you the hex I have on my screen and the key my friend is seen with signal?

**Comment by Blackoverflow** [comment]
> Maybe someone can help me :)

I'll look into it in the next few days.

**Comment by Blackoverflow** [comment]
I just tried the code, including my suggestions, and got the right safety numbers! :)
