### ISSUE TITLE
[BUG] Import of Contacts in Signal Desktop not possible

### ISSUE THREAD

**Issue by nuehm-arno** [nanu-c/axolotl#892]
### Description
Trying to import Axolotl contacts in Signal Desktop is currently not working.

### Steps to Reproduce
1. Open Axolotl with Wifi/4G on.
2. Open Signal Desktop and try to import contacts
3. The wheel is spinning and spinning and spinning...

**Expected behavior:**
Contacts are imported.

**Actual behavior:**
Contacts are not imported.

#### Versions
v1.5.0

#### Device
Mobian@Pinephone and Signal Desktop (Arch Linux 5.56.0-1)

**Comment by olof-nord** [comment]
I see some similarities with this issue and https://github.com/nanu-c/axolotl/issues/768 - if not the same, how do the two differ?

**Comment by nuehm-arno** [comment]
This one is regarding the communication between Signal Desktop and Axolotl. You can choose to import the Axolotl contacts (names etc.) into Signal Desktop to show the right names.
