### ISSUE TITLE
[BUG] Messages sent via Signal Desktop are all synced into one chat in Axolotl

### ISSUE THREAD

**Issue by nuehm-arno** [nanu-c/axolotl#932]
### Description
Messages sent via Signal Desktop are all synced in one chat in Axolotl.

### Steps to Reproduce

1. Open both Axolotl and Signal Desktop
2. Send message to contact via Signal Desktop
3. Check Axolotl

**Expected behavior:**
Message appears in correct chat

**Actual behavior:**
All sent messages appear in one nameless chat in Axolotl

#### Versions
v1.6.0

#### Device
Mobian@Pinephone

#### Link to Debug Log
No logs

**Comment by nuehm-arno** [comment]
Might still be related to
https://github.com/nanu-c/axolotl/issues/653

**Comment by nanu-c** [comment]
Solved via #985
