### ISSUE TITLE
[BUG] Current Issues with Group Messaging

### ISSUE THREAD

**Issue by nuehm-arno** [nanu-c/axolotl#945]
### Description
This bug report tries to collect all current issues with group messaging.

**Creating a new group with Axolotl**
1. No contacts are shown to select for adding (might still be an assignment to the old IDs)
2. Pressing "Create group" results in nothing

**Existing groups**

3. Names in groups are back to UUIDs (regression; was fixed)
4. Sending messages in groups usually fails with this error message

> [axolotl] send to group  unknown group ID
> [axolotl] sending message failed
> [axolotl] SendMessageHelper: send messagemessage  sending failed

--> If messages go through, this log is shown
> failed to handle message, signalingkey has wrong version, please re-register to update your signaling-key
> send message updateMessage: &{53126 125 <nil>  _redactedUUID_ _messageText_ true _timestamp_ 0 1 second ago 0 null true false 0 0 false false false 0 <nil>}

6. Receiving is not possible and leads to complete crash of Axolotl
> [textsecure] [groupsv2] error updating group change from serverstatus code 401 
> panic: runtime error: invalid memory address or nil pointer dereference
> github.com/signal-golang/textsecure/groupsv2.HandleGroupsV2

--> and after a restart of Axolotl
> [textsecure] Failed to handle received message error="invalid message:  no valid sessions"

--> Sometimes this error messages occurs without a complete crash
> [textsecure] Failed to handle received message error="[textsecure] handleReceivedMessage content length is 0"

**Syncing with Signal Desktop**

7. Created groups with Signal Desktop are not shown in Axolotl
8. Sent messages in self-created groups via Signal Desktop are sometimes shown in Axolotl inside the "Me" contact

#### Versions
v1.6.0 - HotFix (PR 939 with every change until 61f0f40)

#### Device
Mobian@Pinephone

**Comment by rubdos** [comment]
> Receiving is not possible and leads to complete crash of Axolotl

Probably has to do with sender keys. See WIP at https://github.com/whisperfish/libsignal-service-rs/pull/171

**Comment by nanu-c** [comment]
#985 will solve this problem
