### ISSUE TITLE
[Bug] Add contacts to group

### ISSUE THREAD

**Issue by fabrei** [nanu-c/axolotl#96]
### Description

Creating groups work fine. But if it was created, I can't add additional contacts. There is no possibility in options menu.

### Steps to Reproduce

1. Open existing group.
2. Tap on burger button.

**Expected behavior:** I expect a possibility at options of a group chat.

**Actual behavior:** No possibility to add contacts to an existing group.

**Reproduces how often:** 100%

#### Versions

0.7.0
ut 16.04 ota 11

#### Device
Oneplus One Bacon

**Comment by nanu-c** [comment]
solved in 0.7.3 :)
