### ISSUE TITLE
Editing Group members

### ISSUE THREAD

**Issue by ttxtea** [nanu-c/axolotl#98]
Once a new group has been established. It seems as of yet not possible to add additional members with axolotl.

As far as understand the signal protocal would in general allow this and some other (not UBports) clients seem to have this possibility.

Thx for this wonderful Signal client!

**Comment by ateliernz** [comment]
Do you mean https://github.com/nanu-c/textsecure-qml/issues/96 ?

**Comment by ttxtea** [comment]
Yes, that is the same issue

**Comment by nanu-c** [comment]
It's solved and a duplicate
